apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/tekton-operator
patches:
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: tekton-operator-config
        namespace: flux-system
      spec:
        path: infrastructure/vagari/tekton-operator/config
