k3s_server_config:
  token: "{{ k3s_agent_config_token }}"
  cluster-init: true
  disable:
    - traefik
    - servicelb
    - local-storage
    - metrics-server
  disable-kube-proxy: true
  disable-network-policy: true
  flannel-backend: none
  node-ip: 10.45.16.20,fd45:45:45:10::20
  node-external-ip: 85.208.85.159
  advertise-address: 10.45.16.20
  node-label:
    - topology.kubernetes.io/region=cis-west
  node-taint:
    - node-role.kubernetes.io/control-plane:NoSchedule
