apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-dns
spec:
  interval: 1h
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
  ref:
    semver: "1.20.*"
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/home-operations/charts-mirror.*$"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
