apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix-media-repo
spec:
  interval: 1h
  releaseName: matrix-media-repo
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: matrix-media-repo
  values:
    persistence:
      media:
        enabled: false
    controllers:
      main:
        initContainers:
          render-config:
            env:
              - name: DB_URI
                valueFrom:
                  secretKeyRef:
                    name: matrix-media-repo-db-app
                    key: uri
              - name: S3_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: matrix-media-repo-garage-key
                    key: host
              - name: S3_BUCKET
                valueFrom:
                  secretKeyRef:
                    name: matrix-media-repo-garage-key
                    key: bucket
              - name: S3_REGION
                valueFrom:
                  secretKeyRef:
                    name: matrix-media-repo-garage-key
                    key: region
              - name: S3_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: matrix-media-repo-garage-key
                    key: accessKeyID
              - name: S3_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: matrix-media-repo-garage-key
                    key: secretAccessKey
    serviceMonitor:
      main:
        enabled: true
    configMaps:
      dashboard:
        enabled: true
    datastores:
      file:
        forKinds: []
      garage:
        type: s3
        forKinds:
          - archives
          - thumbnails
          - local_media
          - remote_media
        opts:
          tempPath: /tmp/
          ssl: false
          region: "$S3_REGION"
          endpoint: "$S3_ENDPOINT"
          bucketName: "$S3_BUCKET"
          accessKeyId: "$S3_ACCESS_KEY_ID"
          accessSecret: "$S3_SECRET_ACCESS_KEY"
    config:
      database:
        postgres: "$DB_URI"
      repo:
        jsonLogs: true
      accessTokens:
        maxCacheTimeSeconds: 43200
      redis:
        enabled: true
        databaseNumber: 0
        shards:
          - name: main
            addr: matrix-media-repo-dragonfly:6379
      rateLimit:
        enabled: false
      urlPreviews:
        oEmbed: true
      thumbnails:
        types:
          - image/jpeg
          - image/jpg
          - image/png
          - image/apng
          - image/gif
          - image/heif
          - image/heic
          - image/webp
          - image/bmp
          - image/tiff
          - audio/mpeg
          - audio/ogg
          - audio/wav
          - audio/flac
    route:
      main:
        enabled: true
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: ListenerSet
            name: external
            namespace: gateway-system
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /_matrix/media/
              - path:
                  type: PathPrefix
                  value: /_matrix/client/v1/media/
              - path:
                  type: PathPrefix
                  value: /_matrix/federation/v1/media/
              # gently stolen from
              # https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/roles/custom/matrix-media-repo/defaults/main.yml
              - path:
                  type: RegularExpression
                  value: ^/_matrix/client/(r0|v1|v3|unstable)/logout(/all)?$
              - path:
                  type: RegularExpression
                  value: ^/_matrix/client/(r0|v1|v3|unstable)/admin/(purge_media_cache|quarantine_media/.*)$
            backendRefs:
              - identifier: main
