apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: matrix-media-repo-garage
spec:
  repository:
    kind: ClusterRepository
    name: external
  credentialProjection:
    enabled: true
  copyMethod: Direct
  sources:
    - pvc:
        name: matrix-media-repo-garage
  retention:
    keepLatest: 3
    keepDaily: 7
    keepWeekly: 2
  compression:
    compressor: zstd
