apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: matrix-media-repo-db-nightly
spec:
  policyRef:
    name: matrix-media-repo-db
  schedule:
    cron: "H 2 * * *"
    jitter: 30m
    runOnCreate: false
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: matrix-media-repo-garage-nightly
spec:
  policyRef:
    name: matrix-media-repo-garage
  schedule:
    cron: "H 2 * * *"
    jitter: 30m
    runOnCreate: false
