apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-secret
type: Opaque
stringData:
  encryption-key: ENC[AES256_GCM,data:fc0YwgEDuj8VAIGpyaA+gCGyGwmFA+F2YiWmHnFdMWJS1lT7JiQANr01Ln4=,iv:grH00UMCXbRFh73pXNW3ejAyQnItbZpTm7OtRLxpUk4=,tag:xyX0r08rjtOBxoKzKl9+4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWnliTEdtZm9Ca2tEQ0V2
        bVBhd1ltdWZncEZCc0ZKd2lEUTB0UjJ6S0NBCnFzZXlsL0tDWWJDcFluTEViY3VW
        T21XRkhCQmEzY01Lb2lxeGxTVkFRWjgKLS0tIHd5aG9jRmhTTFEyb1dLNTQyMlZw
        R1g0UjgwendTaEdscmcyZnd0YlpoMFUKDrD6lkG6E7jsWcE0AU/dWQ/kDzaYB75t
        emQ5m5mLTbVvfyC2IVR3YCL82E6o34SXAodnKrKtHs7rkcHS4fHJBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-18T11:09:06Z"
  mac: ENC[AES256_GCM,data:kkbjf04sh9IpaEf6nRDvArLsB0iEiUYOmGtuoUlV3uKgFOFgz6TIRDU7mRcrby2d1p9+nFtIUhfHSSCG87HdVycvEX/Zus/lG3jgMEBDjzCILXLWBR0dldb6RFTSj+n/Rttj/NEl4H+S5VqfJWTIB8sAuqoms3VsakhqxSh69ns=,iv:vf5ltH4dZJEPDCLlCLJh/GdLtqjWFligaK9VnS66ewo=,tag:gyvxDcLekUt5GA79Q3nxCQ==,type:str]
  version: 3.13.3
