apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
type: Opaque
stringData:
  nextcloud-username: ENC[AES256_GCM,data:X2zwvcg=,iv:a30N2H7N1poiwCfz646gKw9evaIBqlr/Q1xVIC3CeYo=,tag:S3KEDno4oU+cQRzW+vmRAQ==,type:str]
  nextcloud-password: ENC[AES256_GCM,data:iLjk4ThoZ95oCiSF,iv:/3esyvbs/XbyaYKyjHgXXi38WrQazXYuTcold4fYobQ=,tag:6cTc4saqJwlZMcQqPyTKNQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MnJTOHlLQW9xVmZuWk5P
        M0Zld2Jsc2F5U0h3T3N5R3ZXMmZtUldzckdjCkxqclBwMEs3UC9hOHRscWwyZWJx
        UjdPK1VwbGtnUzZTa3FQdklUbFp4dnMKLS0tIGJlNmRnTGZrci9BeUJvU1czVmtT
        bzZPRWJ1VXVSS0hnYStTL1NzZytNOWsKcyn17iPcqKRqDYfcMSsXGhHsCuwTcmEW
        TBse2UTOvAEQiV2sbZ9hDgP+/Cz5dyOOuxjoJ0l9MHFcDvmnwhhx9w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age194uq3r4zu3kjllp8x947yjk0h0hj33v82qwyged2hczzywrc0spsw9vxer
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-03T16:21:01Z"
  mac: ENC[AES256_GCM,data:Xh3Pu3kcu2JgPLIYKOpgdPFkKK9sTbVr8SGzhL/o2QsND67hnKc8TU6RPKrPbZrVgIGxWyQWNAJnaMjTYdIWLIjNlCYsR4388PrNbOelaq1UJaoV1CPtuQ4ArDIzCPDQn59FJVyEN3YPBjyQboI84rypNWWM7EJnC6bfnln73mA=,iv:fVsyyAbNOGI4PXAqhjH1VKnTSRlS3SnhuqCATKdzmkM=,tag:1Sejcycrg4fRSsZeRBst6w==,type:str]
  version: 3.13.3
