---
- op: add
  path: /spec/patches/-
  value:
    target:
      group: garage.rajsingh.info
      kind: GarageCluster
      name: garage
    # language="yaml"
    patch: |-
      - op: add
        path: /spec/storage
        value:
          data:
            size: 100Gi
            storageClassName: longhorn-local
          metadata:
            size: 10Gi
            storageClassName: longhorn-local
