apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
spec:
  interval: 1h
  releaseName: dragonfly-operator
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
  values:
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
