---
singbox_config_inbounds:
  - tag: tun
    type: tun
    stack: mixed
    address: 172.19.0.1/30
    auto_route: true
    strict_route: true
    auto_redirect: true
    auto_redirect_input_mark: "0x2023"
    auto_redirect_output_mark: "0x2024"
    route_exclude_address:
      - 10.42.0.0/16
      - 10.43.0.0/16
      - 10.45.0.0/16
    endpoint_independent_nat: false
    interface_name: sb0
