apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/gateway-api/kustomize
patches:
  - path: patches/no-https.yaml
    target:
      group: gateway.networking.k8s.io
      kind: Gateway
