---
- op: add
  path: /spec/patches/-
  value:
    target:
      group: garage.rajsingh.info
      kind: GarageCluster
      name: garage
    # language="yaml"
    patch: |-
      - op: add
        path: /spec/admin/adminTokenSecretRef
        value:
          name: garage-secret
          key: garage_admin_token
