apiVersion: v1
kind: PersistentVolume
metadata:
  name: vikunja-garage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: vikunja-garage
    namespace: vikunja
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: vikunja
    volumeAttributes:
      mounter: geesefs
      options: "--no-systemd --memory-limit 500 --dir-mode 0777 --file-mode 0666"
    nodeStageSecretRef:
      name: vikunja-garage-key
      namespace: vikunja
    nodePublishSecretRef:
      name: vikunja-garage-key
      namespace: vikunja
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-garage
spec:
  volumeName: vikunja-garage
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
