---
- op: add
  path: /spec/patches/-
  value:
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: gotosocial
    # language="yaml"
    patch: |-
      - op: replace
        path: /spec/values/gotosocial/accountDomain
        value: floof.fans
      - op: replace
        path: /spec/values/gotosocial/host
        value: social.floof.fans
