apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cosi
spec:
  interval: 1h
  url: https://github.com/kubernetes-sigs/container-object-storage-interface.git
  ref:
    branch: main
