apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: garage-backup-key
spec:
  clusterRef:
    name: garage
  allBuckets:
    read: true
  secretTemplate:
    regionKey: RCLONE_CONFIG_SOURCE_REGION
    endpointKey: RCLONE_CONFIG_SOURCE_ENDPOINT
    accessKeyIdKey: RCLONE_CONFIG_SOURCE_ACCESS_KEY_ID
    secretAccessKeyKey: RCLONE_CONFIG_SOURCE_SECRET_ACCESS_KEY
