apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage-backup
spec:
  interval: 1h
  releaseName: garage-backup
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: rclone
  values:
    controllers:
      main:
        containers:
          main:
            args:
              - sync
              - "source:"
              - "compress:"
              - --verbose
              - --fast-list
              - --checkers=8
              - --transfers=8
            envFrom:
              - secretRef:
                  name: garage-backup-key
              - secretRef:
                  name: garage-backup-secret
    config:
      source:
        type: s3
        provider: Other
      target:
        type: s3
      alias:
        type: alias
        remote: "target:"
      crypt:
        type: crypt
        remote: "alias:"
      compress:
        type: compress
        remote: "crypt:"
