---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../base/configs/cert-manager
patches:
  - path: patches/letsencrypt.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
