apiVersion: v1
kind: Secret
metadata:
  name: garage-secret
type: Opaque
stringData:
  admin-token: ENC[AES256_GCM,data:2J2PN4hryXndAZgIqaHMOA07iiPHRG1JG6jqH3BZDJs8N79ZX28KqX9d44hqaiXfgjLymXDkwfx7fmKf3JKngQ==,iv:n28Ww5feuFhbXjUYfcHJ2F9Ej0AOU4vzofc8HlyLuNw=,tag:zjPfw3gT8bd14P6Z6Pym3w==,type:str]
  rpc-secret: ENC[AES256_GCM,data:u10KvfDRY3rqNPL8xwqhTz4y+zJsShPzkuP6MaqCLcSoBH9i0/17ycq9ibellzGp+IKMcNxEtd+Z92yyJJD8XA==,iv:jWFqIf4rIpDXUWgWBOiH56jNghbRVVodHTs2hmI/K/c=,tag:fjf1xxvZv2ctag3intdvJA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNEN3K1R5VjZzUHUyQktB
        VFZSQmNUelVsd2NPMDZraFU5MTBmL3pBN1N3CnA3N0hwS05XT0JYa21ETGdwUlVN
        NFVlQnJtZDBFb0k1WEZTcUlSbFREbkkKLS0tIG9WNmZCcndBalAvTWwrTHdzck1n
        cVRNWUNScXl5dFB3M1RHSmJNSEwzOWMKleddRdYmut9JYfvSoIDdsD9/D1lA4Lwh
        ZLCGeZbXpu86Xvc0pw9OI6BxrcIS5cd+oivdmhFeXjhBX5M+Izsbtg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T20:56:35Z"
  mac: ENC[AES256_GCM,data:GpBNyndftUS+mwZ5ASfOSCaJ39K2zCtKOfOJtYdFL3U1LWK5jhvSxpGbNt+diFLXT9m8/tbkBxrWeCbR0fvbUeBfTvQ6jLsLuZU2a4bbZDEvjfstdVYKs08IeUQRY8LMmT3Yweo4u726hDaSFiiFPuEryCyWdZQu8CmeMCuUVuM=,iv:sUgXuHHWlXa79Ml3U+RQQP3Meick/Sovvs8D9ozulm4=,tag:3qctPwUCkodyxS/BCwoIVA==,type:str]
  version: 3.13.3
