apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: gotosocial-db-nightly
spec:
  policyRef:
    name: gotosocial-db
  schedule:
    cron: "H 2 * * *"
    jitter: 30m
    runOnCreate: false
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: gotosocial-garage-nightly
spec:
  policyRef:
    name: gotosocial-garage
  schedule:
    cron: "H 2 * * *"
    jitter: 30m
    runOnCreate: false
