apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
type: Opaque
stringData:
  cloudflare-api-token: ENC[AES256_GCM,data:dEV6wr6z5NPIOGmEIhf5Swt3TjgKy/FbNjMpP2o3Z6o5jyZP04oh2sg4krHY2Et3yLuReGs=,iv:7p9TeLKix4EA2ap51itHcHo/uD7YyH+tErLMTIeBAwE=,tag:u9d0I7MhTJ9bGSp7WTmX4Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWblRrY2pnY1VFKytVV0My
        SS9zQ1BmdGdHZ3JScnU0b3FpT3VPSExFSldrCkw3MWQrcmFNUzF6OTFnTk1zamF2
        bTJnZURpc0NLenJuc3F0V0FVYW00WGcKLS0tIGRnSHVrVG1zZVVnYjFoMFpnUEZW
        eFNPMS9rOHJqRWFOV0llWG5uZUlqVEUKhckGNQomEwlesiOd8u/l/6OrNUprz/i8
        ZlCxmbYZTKWuSe03JZRaSvSdXFbq3z5sVfk+M0hmuNBTt+3DWNtGsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T10:59:49Z"
  mac: ENC[AES256_GCM,data:JFtuAza8BlmgAHUTxX/dNxMOQZtNV8VVV7zDMPzuATMNIhYvy2x5C2MvmA74btZ3+kBgvoGwOrjthabsAMIk2Uc0+LtqZ3YmP4U0XyCjLnMwYuHU2eUo4zlw6kkinEtwBk1zgI1/ZK9lrNOyizXTwT720tOmOC8OPP3N60P57z0=,iv:WsMb2XmGLdLHp7s6dmJR4gWZcvLSa+9KEDRjxdQCkt4=,tag:BYW5/ZENP2wsyN0fmKI60g==,type:str]
  version: 3.13.3
