apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
type: Opaque
stringData:
  cloudflare-api-key: ENC[AES256_GCM,data:S41xMOLxxpZCZJrB0zTQirFjoQAdmRTzaOJFlCDPOLF7VcNDLEblX7Qvg6K2ju19qZP3xIc=,iv:7PODWpBfsKYIECpKfZ3x8dL+++XLhlXZiU7I6Oo8iKs=,tag:ds5FOgqBIcMZ1ERXy4ci2A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWblRrY2pnY1VFKytVV0My
        SS9zQ1BmdGdHZ3JScnU0b3FpT3VPSExFSldrCkw3MWQrcmFNUzF6OTFnTk1zamF2
        bTJnZURpc0NLenJuc3F0V0FVYW00WGcKLS0tIGRnSHVrVG1zZVVnYjFoMFpnUEZW
        eFNPMS9rOHJqRWFOV0llWG5uZUlqVEUKhckGNQomEwlesiOd8u/l/6OrNUprz/i8
        ZlCxmbYZTKWuSe03JZRaSvSdXFbq3z5sVfk+M0hmuNBTt+3DWNtGsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T21:27:34Z"
  mac: ENC[AES256_GCM,data:Da3ZG5CD599BGJScOgsIU9arbT1tEGkLEPhs5REabXSfmZX6hTmyi0AEr5NAaA5UMn20RTPXkmGoX5JxkTZmV3xr7yVk2DjAXqX7dMSvCKcMjZLAGKqIqS4hnWFoVO82WUkTa89AUG3PMEjJ4+szcOpM4vmtl/44mMkEHgwvX90=,iv:OexeMjFE6PpHDEvAZwvQapVIPwgXDvr+xWxBPTq6OI8=,tag:Ff2caew/8+trGv1iXrkv+A==,type:str]
  version: 3.13.3
