apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${NAME}-garage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: ${NAME}-garage
    namespace: ${NAME}
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: ${NAME}
    volumeAttributes:
      mounter: geesefs
      options: "--no-systemd --memory-limit 500 --dir-mode 0777 --file-mode 0666"
    nodeStageSecretRef:
      name: ${NAME}-garage-key
      namespace: ${NAME}
    nodePublishSecretRef:
      name: ${NAME}-garage-key
      namespace: ${NAME}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${NAME}-garage
spec:
  volumeName: ${NAME}-garage
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
