apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: s-ui
spec:
  values:
    listenerSets:
      main:
        parentRef:
          group: gateway.networking.k8s.io
          kind: Gateway
          name: external
          namespace: gateway-system
