apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: s-ui
spec:
  values:
    pod:
      nodeSelector:
        net.kasefuchs.homelab/region: eu
        net.kasefuchs.homelab/placement: cloud
