apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: s-ui
spec:
  values:
    route:
      grpc:
        enabled: true
        kind: GRPCRoute
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: ListenerSet
            name: external
            namespace: gateway-system
      reality:
        enabled: true
        kind: TLSRoute
        parentRefs:
          - identifier: main
        rules:
          - backendRefs:
              - identifier: gateway
                port: reality
