apiVersion: v1
kind: Secret
metadata:
  name: garage-backup-secret
type: Opaque
stringData:
  RCLONE_CONFIG_CRYPT_PASSWORD: ENC[AES256_GCM,data:TcuEjvuxB8JTTJpjGUKwrbXAeQzvEsBVeayslB5cOuASL7zxyQ0=,iv:vWu7QzmoUNaj/752fU1JOPtm1eTmtRlEQFunX/8ifm4=,tag:Y+7G/7CO6zUoe92o6IflvA==,type:str]
  RCLONE_CONFIG_TARGET_ACCESS_KEY_ID: ENC[AES256_GCM,data:wPKzydiu/zTNT6e4,iv:D3Apzp6n+tE0jFKH+sMxGDCcZWA/Cc7tFvOxpVspx/w=,tag:5RZFWcjdPwmj7aeW2MqmNA==,type:str]
  RCLONE_CONFIG_TARGET_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lY/qakrBHATMOird9x6oW5rK1+kKFaU1GX9PvA==,iv:A8cwBJrkN256OeP98zhlikYseaOxMwZIl8V4Y4nY6t4=,tag:6lMNpbIHztTaGh/WtdVpOg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVlB4RVIxMEdyWHl5bXYw
        MVZ5cTZpVkt6TGROVFZOczNNNTIzcnBPZkJBCm5xVnNVTkFPNU9TTC9YT2t3d3RG
        c2FRK2QvOEo4d3dUQjhkWit2V0dsNDgKLS0tIDJhNU5yVVd4WG05cVRFWFBEbWRR
        S2k3cDlQOTl5TkEyc29tc2xkaG5TbGcKNVO/kiwRAEqUl9VC04L2+u7J5QpIScKV
        vzBFP5H4YqONAiumKbM6qAaYz2n5goL8t1LZmAkozWRVQt8jN02PLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tfa0m86eq3r4putn2dn8ddswexj6k6mawjwxcqtauqr5792jtujqxtpwn9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T21:07:05Z"
  mac: ENC[AES256_GCM,data:mUD2sslnnz9+5k58rsq4Fb0T447+EZfxaHozN1ew6MBYeSuCaxeI/hWTkcjgF9ceRFgZqdzcCoyfnphhM/Otndjl+hxG0A0w72P1FvUhQ3jdS5nwUi/EfCgFfEoYv9RYcPiVI0ZVhswjAFV0kqu3wT1Ib7E9EGPrCe6R3ysYS1U=,iv:xjortn3HV3h8gSTywz/yro4dDTUccoFp1TsJdFEGeuE=,tag:AHOFszXGk+zctw41dpJLew==,type:str]
  version: 3.13.3
