apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  values:
    route:
      hostnames:
        - renovate.kasefuchs.net
    webhook:
      route:
        hostnames:
          - renovate.hook.kasefuchs.net
