apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/kusai-mastodon
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      name: kusai-mastodon-app
    patch: |-
      - op: replace
        path: /spec/path
        value: apps/production/kusai-mastodon/app
