apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: external
spec:
  listeners:
    - name: https-vagari-apex
      hostname: vagari.homelab.test
      port: 443
      protocol: HTTPS
      allowedRoutes: &allowed-external-routes
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.networking.k8s.io/route-access-external: "true"
      tls: &vagari-tls
        mode: Terminate
        certificateRefs:
          - name: vagari-tls-secret
            kind: Secret
    - name: https-vagari-wildcard
      hostname: "*.vagari.homelab.test"
      port: 443
      protocol: HTTPS
      allowedRoutes: *allowed-external-routes
      tls: *vagari-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: internal
spec:
  listeners:
    - name: https-vagari-wildcard
      hostname: "*.vagari.homelab.test"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: vagari-tls-secret
            kind: Secret
