apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${NAME}-db-barman-garage-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cnpg-system
  target:
    name: ${NAME}-db-barman-garage-key
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: plugin-barman-cloud-garage-key
        property: accessKeyID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: plugin-barman-cloud-garage-key
        property: secretAccessKey
