# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-crd
spec:
  path: infrastructure/base/envoy-gateway/crd
  wait: true
  prune: true
  timeout: 10m
  interval: 1h
  retryInterval: 2m
  targetNamespace: kube-system
  sourceRef:
    kind: OCIRepository
    name: flux-system
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-controller
spec:
  path: infrastructure/base/envoy-gateway/controller
  wait: true
  prune: true
  timeout: 10m
  interval: 1h
  retryInterval: 2m
  targetNamespace: &namespace envoy-gateway-system
  sourceRef:
    kind: OCIRepository
    name: flux-system
  dependsOn:
    - name: envoy-gateway-crd
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      NAME: envoy-gateway
      NAMESPACE: *namespace
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
