apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cilium/controller
patches:
  - path: patches/device.yaml
  - path: patches/hubble.yaml
  - path: patches/kube-proxy.yaml
