apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
spec:
  distribution:
    version: 2.7.x
    registry: ghcr.io/fluxcd
    artifact: oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
  cluster:
    type: kubernetes
    size: small
    domain: cluster.local
    multitenant: false
    networkPolicy: false
  sync:
    kind: OCIRepository
    url: oci://docker:5000/homelab/flux
    ref: latest
    path: clusters/vagari
    interval: 1m
  kustomize:
    patches:
      - # language="yaml"
        patch: |-
          - op: add
            path: /spec/insecure
            value: true
        target:
          kind: OCIRepository
