apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: ${NAME}
spec:
  launchUrl: https://vikunja.${CLUSTER_DOMAIN}
  callbackUrls:
    - https://vikunja.${CLUSTER_DOMAIN}/auth/openid/pocketid
  secret:
    keys:
      issuerUrl: VIKUNJA_AUTH_OPENID_PROVIDERS_POCKETID_AUTHURL
      clientID: VIKUNJA_AUTH_OPENID_PROVIDERS_POCKETID_CLIENTID
      clientSecret: VIKUNJA_AUTH_OPENID_PROVIDERS_POCKETID_CLIENTSECRET
