apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/bucket-access-class.yaml
  - resources/bucket-class.yaml
  - resources/cluster.yaml
  - resources/namespace.yaml
