apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  values:
    web:
      ingress:
        enabled: true
        className: traefik
        annotations:
          external-dns.alpha.kubernetes.io/hostname: traefik.kind.local
        hosts:
          - host: flux.kind.local
            paths:
              - path: /
                pathType: Prefix
