apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
spec:
  interval: 1h
  url: oci://ghcr.io/traefik/helm/traefik
  ref:
    semver: "39.0.*"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
