apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 1h
  releaseName: nextcloud
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: nextcloud
  values:
    x-container-security-context: &container-security-context
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      existingSecret:
        enabled: true
        secretName: nextcloud-db-app
        hostKey: host
        databaseKey: dbname
        usernameKey: user
        passwordKey: password
    nextcloud:
      host: nextcloud.example.com
      objectStore:
        s3:
          enabled: true
          ssl: false
          host: garage.garage.svc.cluster.local
          port: 3900
          region: garage
          bucket: nextcloud
          usePathStyle: true
          existingSecret: nextcloud-garage-key
          secretKeys:
            accessKey: access-key-id
            secretKey: secret-access-key
      configs:
        dataperms.config.php: |-
          <?php
          $CONFIG = array (
            'check_data_directory_permissions' => false,
          );
      extraVolumes:
        - name: confd
          emptyDir: {}
        - name: tmpfs
          emptyDir: {}
        - name: apache
          emptyDir: {}
      extraVolumeMounts:
        - name: confd
          mountPath: /usr/local/etc/php/conf.d/redis-session.ini
          subPath: redis-session.ini
        - name: tmpfs
          mountPath: /tmp
        - name: apache
          mountPath: /var/run/apache2
      extraInitContainers:
        - name: init-confd
          image: busybox:1.37.0
          command: ["touch", "/usr/local/etc/php/conf.d/redis-session.ini"]
          volumeMounts:
            - name: confd
              mountPath: /usr/local/etc/php/conf.d
          securityContext: *container-security-context
      securityContext: *container-security-context
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 33
        fsGroup: 33
    redis:
      enabled: false
    externalRedis:
      enabled: true
      host: nextcloud-redis
      port: 6379
    persistence:
      enabled: true
      size: 10Gi
    cronjob:
      enabled: true
      sidecar:
        securityContext: *container-security-context
    livenessProbe:
      initialDelaySeconds: 30
    readinessProbe:
      initialDelaySeconds: 30
