apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: nextcloud-redis
spec:
  kubernetesConfig:
    image: valkey/valkey:9-alpine
    imagePullPolicy: IfNotPresent
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    runAsUser: 999
    fsGroup: 999
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ALL]
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
