apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${NAME}-db
spec:
  storage:
    size: 20Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  values:
    persistence:
      size: 15Gi
