apiVersion: v1
kind: Secret
metadata:
  name: garage-secret
  namespace: garage
type: Opaque
stringData:
  garage_admin_token: ENC[AES256_GCM,data:jKI2QyBECJ54m6ipX3VOVxyNY6AEUN36m+Y92bkTT8IS+QFLufnos0PxsdX1wzKg0YKpbAF4SugUG1AOomxqhQ==,iv:97BC5i61PFd1XCe6P0aDfytvKCkVOR3ErBQXoWzlnqU=,tag:5/fiPSDUTCo/eV2+bba2dg==,type:str]
sops:
  age:
    - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U3pyMEdpSHB3MitMemxx
        Sk8zM3BFN1dDbUN4MEpBWGxQNjRxMG9sRWdVCmhFZk5MbUtqWkhQaTl3Mm9BSC9h
        eVVxMURHQTRoaVJodzJEc3lrZEprekEKLS0tIDhZMHJaRlZ4amJnN29NYVo0L3ds
        RUNxaFk5aDhVTHQ5MXMydEJhMHlFUjAKxij65Z01WktVUWYPD7cOaitsd75VcJ9r
        A3ZRCzM6/yIfkuimn71bNWl3i06XAhDFlG8ozxdoRM37b/EWdFA2hQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcktPVldKZGVQek1XaytJ
        M2pBYzJOMmJaSlNiZ0F3ODJvRmo0MFlpczM4CmJkL1lLUEVaamEwelpVU3R3Qy9s
        bkJ4UDJ1TWlFajFYaDRKNnNBOTF6b2sKLS0tIDVvcnlYVUVSY3I4WkllTFBTYjVK
        N1hLYXA4MThYZGp2VzJMWXlBSHRZWXMKc/1h5THquvwPVDi8D+LgjVPqyqHe5CBQ
        IS4OS3q957+N4YhXun4sccMrh7IKodnHg4AZofPM2euavr2AgT0lsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T19:21:11Z"
  mac: ENC[AES256_GCM,data:XLR6QqVb06Wl0guvrNDvAyFhhxiRzjFj2tiYtK6yImhHWrYU9rczsMP9k3bUxl4MGiJ8HBG8uGp2+wZGs5BWKUDkGzbyKdUCeytO+CzFUNjpp/XVF6NEF5Bpw4eUEhO1O4zgGqSTUqYkTwc10fV8+1g6gv4t349Lt9AMVwHEHuY=,iv:nRImlDnaW5EZR50wl7T9MX+1rgc3Art4e+9PVx2LKcQ=,tag:RXyvLkAGBnD/Wd8rFW5pLw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
