apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-garage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: nextcloud-garage
    namespace: nextcloud
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: nextcloud
    volumeAttributes:
      mounter: geesefs
      options: "--no-systemd --memory-limit 500 --dir-mode 0777 --file-mode 0666"
    nodeStageSecretRef:
      name: nextcloud-garage-key
      namespace: nextcloud
    nodePublishSecretRef:
      name: nextcloud-garage-key
      namespace: nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-garage
spec:
  volumeName: nextcloud-garage
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
