apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: nextcloud-garage-key
spec:
  clusterRef:
    name: garage
    namespace: garage-operator-system
  bucketPermissions:
    - bucketRef:
        name: nextcloud-garage-bucket
      read: true
      write: true
