apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${NAME}-db
spec:
  storage:
    size: 15Gi
  managed:
    services:
      disabledDefaultServices:
        - ro
        - r
  bootstrap:
    initdb:
      owner: ${NAME}
      database: ${NAME}
  postgresql:
    parameters:
      max_slot_wal_keep_size: 3GB
