apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/s-ui/app
components:
  - ../../../../components/pvc/components/backup
patches:
  - path: patches/route.yaml
  - path: patches/placement.yaml
  - path: patches/service.yaml
