apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/pocket-id/config
  - resources/secret.yaml
  - resources/user.yaml
components:
  - ../../../../components/cnpg/components/backup
patches:
  - path: patches/config.yaml
  - path: patches/route.yaml
