apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  interval: 1h
  releaseName: victoria-metrics-k8s-stack
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: victoria-metrics
  values:
    x-security-context: &security-context
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
      seccompProfile:
        type: RuntimeDefault
      fsGroup: 65534
      runAsGroup: 65534
      runAsUser: 65534
    prometheus-node-exporter:
      enabled: false
    victoria-metrics-operator:
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
    vmagent:
      spec:
        securityContext: *security-context
    vmalert:
      spec:
        securityContext: *security-context
    vmsingle:
      spec:
        securityContext: *security-context
    alertmanager:
      spec:
        securityContext: *security-context
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
spec:
  interval: 1h
  releaseName: prometheus-operator-crds
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: prometheus-operator-crds
