apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics
spec:
  interval: 1h
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
  ref:
    semver: "0.74.*"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
