# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-controller
spec:
  path: infrastructure/base/external-dns/controller
  wait: true
  prune: true
  timeout: 10m
  interval: 1h
  retryInterval: 2m
  targetNamespace: external-dns
  sourceRef:
    kind: OCIRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      NAME: external-dns
