apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-tls
spec:
  secretName: staging-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
  dnsNames:
    - "*.staging.homelab.test"
    - "*.web.garage.staging.homelab.test"
