---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/secret.yaml
  - ../../../../../base/services/garage
patches:
  - path: patches/admin.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
  - path: patches/storage.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
