amneziawg_config_interface_host:
  Address: 10.45.16.24/24, fd45:45:45:10::24/64
  ListenPort: 48761
  PrivateKey: "{{ amneziawg_config_private_key }}"
amneziawg_config_peers:
  # silky
  - PublicKey: "{{ amneziawg_config_public_keys.silky }}"
    PresharedKey: "{{ amneziawg_config_preshared_keys.silky }}"
    AllowedIPs: 10.45.16.20/32, fd45:45:45:10::20/128
    Endpoint: silky.kasefuchs.net:48764
  # mala
  - PublicKey: "{{ amneziawg_config_public_keys.mala }}"
    PresharedKey: "{{ amneziawg_config_preshared_keys.mala }}"
    AllowedIPs: 10.45.32.16/32, fd45:45:45:20::16/128
    Endpoint: mala.kasefuchs.net:48248
  # esmae + lestat
  - PublicKey: "{{ amneziawg_config_public_keys.esmae }}"
    PresharedKey: "{{ amneziawg_config_preshared_keys.esmae }}"
    AllowedIPs: 10.45.224.24/32, fd45:45:45:e0::24/128, 10.45.16.16/32, fd45:45:45:10::16/128
