apiVersion: v1
kind: Secret
metadata:
  name: garage-backup-secret
type: Opaque
stringData:
  RCLONE_CONFIG_CRYPT_PASSWORD: ENC[AES256_GCM,data:jSLlnMeLRk2VmA0V+ew5uOOyLx6c1Rv47rCQmdHD/eF8h1PYStc=,iv:Ye/k4NyAU68rlZY85kNa7XN7klQD3sDWo/bBCtpYQk0=,tag:HEIoa4m78pCPJaNBJC39Aw==,type:str]
  RCLONE_CONFIG_TARGET_ACCESS_KEY_ID: ENC[AES256_GCM,data:Q5L3XRqoGT35zzYQ,iv:3mNERVQisYURZT/UOQrBJxwuOCIFWu/KxjU10udhFGI=,tag:1rpdh7rUcENsmH9/SyE/VQ==,type:str]
  RCLONE_CONFIG_TARGET_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XecZldUxEXrVHYXCnIfcys8coCSobZpY/q2TTg==,iv:zf9xz1c6gsUSQVtvv3MjPOBDZn/ROYQ4Th40IKwvGoA=,tag:ouN4OV9XiFiUJc6ljwGGGw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TlJrMUdkZDlpT3dvQ2tk
        aHZmdmw2WmFPYVhGMTY5RGRFQXlMRXUzZnlJCkFVRzcvNitBNktFQzRGOUVQcVg4
        ZTNWOXRhSkxNYWNvcWg3OXlEU3lsY0kKLS0tIFBkWFYzTmJWSG5CN2JvUVBWTElq
        T29lODgzL0RuRlowcGNZZFVPY1MyRE0KUCG5rUmf/ItO1HT4QACEfAUoQIf+35tN
        9m0FlUJyN4zBqkr01R+qlEnXbNdNnC/8aWhmtbXaRdB3WwE4XsvWpw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age194uq3r4zu3kjllp8x947yjk0h0hj33v82qwyged2hczzywrc0spsw9vxer
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T21:07:17Z"
  mac: ENC[AES256_GCM,data:Rpuxa4lb7ROm/h3+BHmSBb6MNIO/5zpwYyNdOmhaqRbhJi2uux7XuebKumBoH6x9O8VUWauc6orl4FUBXIi14dtI+2hsd8pMSZS5dCG8ksDlpIfbrPfIEZSVCOZgEDpQim5Rn/dcw5Nrdag0yFZmu1YSIIW5ra2s689qY+9mSVc=,iv:oBjNCw0nbiZhGLHG41JnbaziIPivrPv5OjnTgrulRN4=,tag:+Th6/a4qcPtDUtEDfnODUw==,type:str]
  version: 3.13.3
