---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/secret.yaml
  - ../../../../base/woodpecker
patches:
  - path: patches/agent.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
  - path: patches/server.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
