apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 1h
  releaseName: cloudnative-pg
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
