apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cloudnative-pg
spec:
  interval: 1h
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
  ref:
    semver: "0.28.*"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
