apiVersion: v1
kind: Secret
metadata:
  name: garage-backup-secret
type: Opaque
stringData:
  RCLONE_CONFIG_CRYPT_PASSWORD: ENC[AES256_GCM,data:72n3kvB3ls3cNT9vvBqUvLkeSwx3DW+ZnPMHHDGJBDVa7dxvRe4lXFFyDpje+mA+aNR8K5pnoPcPp6KlE9CCQw==,iv:cHN5YWQYMyPLowGKTk/Mw7SxnYwj7CdvCd3/TLjYwkg=,tag:Fl0mYlMg4WCNtEVKnSjguA==,type:str]
  RCLONE_CONFIG_TARGET_ACCESS_KEY_ID: ENC[AES256_GCM,data:RjcAHsyD2bWRw4wrXOoIYwK8c6Inb/YK80VTIFziJFVub/MWHkGwl0pn7ctbs4jauSpdnkSTQAIMyQA0+Gq4khtKcJFI,iv:/kYYkuetJCKefcYENC45vQtYZPzpMQQgZ7U5te7jOW0=,tag:xGdL16kb1JVPhd1MqAGz9g==,type:str]
  RCLONE_CONFIG_TARGET_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mfFfPEiInD3cwrzpxeQnKcK2BaK8ziNzbpq6acop2ao=,iv:oiXC3FK5lPVMdU7Y0JLqJMbYWmipfdXmW4BtNgREfXE=,tag:0uWp/VSncj0aDho3y3u1Hg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dzlxNTlvYWRDa0pmZzc2
        VytIYTkyNlpUQ0xDZC8xdjBLSFBTbnlGUGx3CmdydEFNN1RGdUpURmxTK1hQQk5E
        TXhmc0hMNC9aeVlXeDRVVUNIZWl0UlkKLS0tIDRzaTM0SVhuQ0tVWlhtVzFFRkNJ
        WG9yREJXeEJIemxsZlRQMCt3eUxYd2sKZ7oAhxQe1uQ64ZiT1imujbX71eZ0iOCf
        2SfBEA221nGMs6jgqIPQVEHTyN1YlvQYkRi4TOW1VxyqGiJXmZyvlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-04T21:18:46Z"
  mac: ENC[AES256_GCM,data:ShfcA+P/Wso6qeCf+h8b7G74LfXpSYzG9D3fxrZeQGPL7eyGgv2AsWg3hpF6VmyuXY8C6aA+Jfh/mvQM/PnEfQ/enpSgtI/QNFfTWgTMrrtGm2tBiMTwIswD3Emo5p3JeCDDozDfCLK8d2iXdYZWubRFtwCG3RfYZJKCoxEUp0g=,iv:30J+gUbx2uQO7pS0yzVYa6SyPIXcm7nvdFNJ19s1LpA=,tag:LAy09umzYqz44bYHBNl4DA==,type:str]
  version: 3.13.3
