---
apiVersion: objectstorage.k8s.io/v1alpha2
kind: BucketAccess
metadata:
  name: gotosocial-bucket-access
spec:
  protocol: S3
  bucketAccessClassName: garage
  bucketClaims:
    - accessMode: ReadWrite
      bucketClaimName: gotosocial-bucket-claim
      accessSecretName: gotosocial-bucket-access-secret
