---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gotosocial
spec:
  interval: 1h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chartRef:
    kind: OCIRepository
    name: gotosocial
    namespace: flux-system
  values:
    gotosocial:
      host: localhost
      accountDomain: localhost
      database:
        type: postgres
        tlsMode: enable
      storage:
        backend: s3
        s3:
          proxy: true
          useSSL: false
    env:
      GTS_STORAGE_S3_USE_SSL: "false"
    persistence:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: gotosocial-db-app
      valuesKey: host
      targetPath: gotosocial.database.address
    - kind: Secret
      name: gotosocial-db-app
      valuesKey: port
      targetPath: gotosocial.database.port
    - kind: Secret
      name: gotosocial-db-app
      valuesKey: dbname
      targetPath: gotosocial.database.database
    - kind: Secret
      name: gotosocial-db-app
      valuesKey: user
      targetPath: gotosocial.database.username
    - kind: Secret
      name: gotosocial-db-app
      valuesKey: password
      targetPath: gotosocial.database.password
    - kind: Secret
      name: gotosocial-bucket-access-secret
      valuesKey: COSI_S3_ENDPOINT
      targetPath: gotosocial.storage.s3.endpoint
    - kind: Secret
      name: gotosocial-bucket-access-secret
      valuesKey: COSI_S3_BUCKET_ID
      targetPath: gotosocial.storage.s3.bucket
    - kind: Secret
      name: gotosocial-bucket-access-secret
      valuesKey: COSI_S3_ACCESS_KEY_ID
      targetPath: gotosocial.storage.s3.accessKey
    - kind: Secret
      name: gotosocial-bucket-access-secret
      valuesKey: COSI_S3_ACCESS_SECRET_KEY
      targetPath: gotosocial.storage.s3.secretKey
