apiVersion: v1
kind: Secret
metadata:
  name: x-ui-secret
  namespace: x-ui
  labels:
    reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
  reality_route_match: ENC[AES256_GCM,data:d9Bf5xYOjYAoWCbNDRJW/TyRs9Dq+xw=,iv:l9/hF4i0wt/an8Vbk82F72BWbqSdETlnWHR0j2iDDP0=,tag:FsB8or4aV/Y9YfTPmH9yng==,type:str]
sops:
  age:
    - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQVFVNFoxVG5HR2tIc0pH
        ZWduVm5mU0t1elhpZlJKOEZXTm1HcTR1YjFNCnZnRyt2Q1lKSVM0Z282QTNWdFRS
        YmpzWnFEa2t4YUYySVMxL28wQ1lVY1kKLS0tIGt1ZnpVQThqMWtCVThEZ25MMTdO
        bHNXQjhOLzAzejIxNjVQVm5yOThaVFEK3GuatkF7hVj/Jct6YljRK4mEBu9WgAdm
        XqQCS1lMm7UqWdeOjBtXpeU/b1WbUHRWJpKBvrtaJvdfEadB1zVkXQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRVIvUk1aLzdZUWRoOC9C
        a2dFRG42ODAxT3MwblNnM0dQQ2FnbFNDeVZVCjlVY1NJQlJMOGxBVkZLdUtQcUNj
        dkNTUmlnNUtMOHczQTFKUU5LUzIwdk0KLS0tIE95SWNSVkNWZkU2Szhhb1B5WnhH
        Vm5KN21ZY0JDeGdlVHFtdnpXYitGMlkKyRJ/2DX+sdCbmqvASgza8MRDKwz6r4ht
        yGVagPhcG6bkc4nPyCteBNv4ucEa0JKQ2b6vO1hbBfd6SGpEHRGypQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-23T13:32:19Z"
  mac: ENC[AES256_GCM,data:aTO/aQF0gOjb4D8Ok2WVNKOwI8qZ+bi9LIFZFroAuGNNoVXR1OhNI2qUZivy/2sWNDUmOsyqmQBN1tkLP6bDNrPpfCt9vsGqZHi7GOx2V1HwR+SXMFFjecHw8uGv0AUfyihIAvuDZNLz5K2bMflQ4GW8KBW/nDPojVB58Z+orwo=,iv:5DT4XgmCSSGNzdVlHvL18xuvErvTVh7cN6mp6WrJG0w=,tag:Pq29HtDaX14baG+7rLhGOA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
