apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vagari-tls
spec:
  secretName: vagari-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: internal
  dnsNames:
    - vagari.homelab.test
    - "*.vagari.homelab.test"
    - "*.kopiur.vagari.homelab.test"
    - s3.garage.vagari.homelab.test
    - "*.s3.garage.vagari.homelab.test"
    - "*.web.garage.vagari.homelab.test"
