apiVersion: v1
kind: Secret
metadata:
  name: garage-secret
type: Opaque
stringData:
  admin-token: ENC[AES256_GCM,data:m7kRlYgLE/bP4j47NLF7lQtTK84rhrvLBJCbxhyN15EPqsCRNWVQnMiAljNiZit4X87eIRJ1c145v9vQS8dLHg==,iv:BElZ23Zt+u2duqayONoXA6gXNLTTMgpN6vKmjYt4PVQ=,tag:9qTo8IukFe7hrqpYwfN7nw==,type:str]
  rpc-secret: ENC[AES256_GCM,data:oCGtw2Cwf24fwZemqdWwpR6stUVN+wgHVB/YqoWMufdjNqDmKz13gtjlJ/klTFkeTQg19vIlGpj11WWGd7SPFQ==,iv:3d04H9DgR6uKeJxj/MS1eCTwSKQWjq/CeAMUl6+OnmE=,tag:Q4Pzj11SEUjE0enlr6v4EA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaW02TGpWaGN4b0VXNzVm
        aTh3T3RLR0JsZWdvTlZlcU5OVSt5eUFEMURJCmM3M011V0Q0bkNGZitUNTBsc3pm
        MFNqM3NBWGdOYnRRRkpqbENJWnZyRDgKLS0tICtVNDVJYTk0aUJwMjB2QWlja253
        WlpGOWNScXRaTWpBOEtaWXlsMFE0eEkKi5wUnIwn25WsoDU2j7/tafitZ0A6sUpS
        kzR0Ul8daXIyfoYW4SqSTMdm2HzF//XjSDXNGnL7gqqqaKZDF21ExA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tfa0m86eq3r4putn2dn8ddswexj6k6mawjwxcqtauqr5792jtujqxtpwn9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T22:21:59Z"
  mac: ENC[AES256_GCM,data:JNioUlcmDvAEsbf7Pav3DRWC+75EI7lEBIMaWo4HFemjeG+hBzUMTSfFphZkE1MxHetpViIju16JygwL0pkW1FqNIXFVoH5eddHger4Gwc6+A6ZLuBAZxnuzRrCZ2fYSIOKgRnv+3M3BYqRv56umrd8uLoHxZrIU5ndAVFSMxqg=,iv:YM5fP37mlb3d4pbg8QR6/ATlT4moBQwXTDvThBiPzkY=,tag:36kjhKBOduc+Nq4bQHLnDg==,type:str]
  version: 3.13.3
