apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./resources/cert-manager.yaml
  - ./resources/cilium.yaml
  - ./resources/cloudnative-pg.yaml
  - ./resources/flux-operator.yaml
  - ./resources/traefik.yaml
