---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: homelab
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./rootfs/etc/containerd/certs.d/
        containerPath: /etc/containerd/certs.d/
        readOnly: true
networking:
  kubeProxyMode: none
  disableDefaultCNI: true
