services:
  registry:
    image: registry:2
    restart: unless-stopped
    container_name: kind-registry
    networks: [kind]
    ports: ["5001:5000"]
  dns-init:
    image: alpine:3.19
    restart: on-failure
    container_name: kind-dns-init
    entrypoint: /usr/local/bin/entrypoint.sh
    network_mode: none
    volumes:
      - dns-data:/var/lib/bind
      - ./rootfs/dns-init/templates:/templates:ro
      - ./rootfs/dns-init/usr/local/bin:/usr/local/bin:ro
  dns:
    image: internetsystemsconsortium/bind9:9.21
    restart: unless-stopped
    depends_on:
      dns-init: {condition: service_completed_successfully}
    container_name: kind-dns
    networks: [kind]
    ports: ["8053:53/udp", "8053:53/tcp"]
    volumes:
      - ./rootfs/dns/etc/bind:/etc/bind:ro
      - dns-data:/var/lib/bind
    tmpfs:
      - /var/cache/bind:mode=777
networks:
  kind:
    external: true
volumes:
  dns-data:
