version: 3
vars:
  NODES:
    sh: kind get nodes --name homelab
tasks:
  up:
    cmds:
      - docker compose up -d
      - kind create cluster --config cluster.yaml
  down:
    cmds:
      - kind delete cluster --name homelab
      - docker compose down
  pause:
    ignore_error: true
    cmds:
      - for: {var: NODES}
        cmd: docker pause {{.ITEM}}
      - docker compose pause
  unpause:
    ignore_error: true
    cmds:
      - docker compose unpause
      - for: {var: NODES}
        cmd: docker unpause {{.ITEM}}
