version: 3
includes:
  docker:
    taskfile: docker/Taskfile.yaml
    dir: docker
vars:
  NODES:
    sh: kind get nodes --name homelab
tasks:
  up:
    deps: ["docker:up"]
    cmd: kind create cluster --config cluster.yaml
  down:
    deps: ["docker:down"]
    cmd: kind delete cluster --name homelab
  pause:
    ignore_error: true
    deps: ["docker:pause"]
    cmd:
      for: {var: NODES}
      cmd: docker pause {{.ITEM}}
  unpause:
    ignore_error: true
    deps: ["docker:unpause"]
    cmd:
      for: {var: NODES}
      cmd: docker unpause {{.ITEM}}
  setup-registry-proxy:
    cmd:
      for: {var: NODES}
      cmd: docker exec "{{.ITEM}}" sh -c "curl http://registry-proxy:3128/setup/systemd | sed s/docker\.service/containerd\.service/g | sed '/Environment/ s/$/ \"NO_PROXY=127.0.0.0\/8,10.0.0.0\/8,172.16.0.0\/12,192.168.0.0\/16\"/' | bash"
