apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  values:
    grafana:
      envValueFrom:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
          secretKeyRef:
            name: grafana-oidc-credentials
            key: client_id
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
          secretKeyRef:
            name: grafana-oidc-credentials
            key: client_secret
        GF_AUTH_GENERIC_OAUTH_AUTH_URL:
          secretKeyRef:
            name: grafana-oidc-credentials
            key: authorization_url
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL:
          secretKeyRef:
            name: grafana-oidc-credentials
            key: token_url
        GF_AUTH_GENERIC_OAUTH_API_URL:
          secretKeyRef:
            name: grafana-oidc-credentials
            key: userinfo_url
      grafana.ini:
        auth:
          disable_login_form: true
        auth.generic_oauth:
          enabled: true
          name: Pocket ID
          scopes: openid profile email groups
          use_pkce: true
          role_attribute_path: "contains(groups[*], 'grafana-admin') && 'Admin' || 'Viewer'"
          allow_assign_grafana_admin: true
