apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-redis-secret
  namespace: seaweedfs
type: Opaque
stringData:
  redis_password: ENC[AES256_GCM,data:a4DgexuDGyV6qTq83W2ukZkb/nMjVPffYVHHuis0epg=,iv:fVhGiw0hhrglLEJGOYSif4HMLS0WYMjgvistM84MuGo=,tag:NObac/r714QdHFQYRehaCg==,type:str]
sops:
  age:
    - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS1FWeXdZbzZrS0huYWdF
        c2JTa3BmM1BWeTBWcjZNczFXc3A0ZVlLRkQwCnVoTlB1THlEYTBNVXFkUFNjYk5Z
        YVJPRGh2TVgvSThDSndWdG1kU2hjSk0KLS0tIEkyY2Z3Z1dWN3hYaEJ2R3pUSmNF
        MldoUmZOazkwRE1jTThDT3B4Z0dZZmcKx2d0RkhaE0u9xqpDEpcievHSU3JNrLry
        SeH1yE0bMafkuTbqXKKzBnzi+iGYf+1d+hlPh3p+H5ne4i7KRzoq3A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TFVyTlJMYWh3T1lWbTNt
        enB3dm9JRi9FVndaRXIyVUlHZkozU3gzbkhFCm9MNXRQUE9lQ2g4TUprMjZ6N0RH
        TEhWK1lJb3hZUTBSekhNblRTdjFERVEKLS0tIDVvVk42bzdZdDdGR2xHYW5Xemlv
        KythWmdGSmYxT0FyZGh3Ykt6c2ZmRTAKd20fhYTzIqWAIYHMbNuGlBfBUchbJ49i
        Qkl9wtOsBFzkRPZrHVCap8pQ4xO2wYqfZJ8pR6VRHwhpRj1Vy2ptCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T18:11:27Z"
  mac: ENC[AES256_GCM,data:2UzN/MTnujHUyXKjqoWmEJPygcGF3hx0g3dyCWdPJ7FYHXB9celX+KsuKA87jcXavh0qrEUm/oKagmCXhZ/FZKN79AFkWmwoVwwf+jSGnoeHg9GwXfPWMFLyysUhs2eVLZfNPK8TyxqLJXCOAsv7FX97eH/KhEGGhK83Wr79EHg=,iv:6Tr9pETo0OAtiFIfGwBOjfErzDQWtGPfd6t/lwQ1Efw=,tag:3eNeSY9IOZ1oQ0St1Q4IqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
