apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-secret
  namespace: seaweedfs
type: Opaque
stringData:
  seaweedfs_s3_config: ENC[AES256_GCM,data:ahGNbGbirg3C9WgOpdq5a7f6ruQMAA==,iv:ECu3MhMscrw4nDynXTZXIs3i1eNtxUxPG6dwuH3XvgI=,tag:A0ksV6VJzAAy9Cc7DmBeZA==,type:str]
sops:
  age:
    - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYlVFbUd1cXFqRmVYV2pQ
        VFAyZUthbHZvZnRVUmhyeTNWc1l4V1VjaGdVCkFVd0Jyc1U0VmVtWXd4L3B0YW5K
        Y0VuUjZaTm5yeXIwSm1vVlpKQ2FIb3cKLS0tIG9ROG1ZenczTVRub00welI4cFRj
        V0QxRzhEdm9yL2xWUGhBWlpCaXo5OUUKx4ZYABcTM3ZDKdUeYui7JBqppBuroTmZ
        jfM6iVtB1816h2z1k2CBEM+EQqRdQUdmhOra5HXfR8JQcGcxDSrnlQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZ1UwZS9FTUlZOXV5TWha
        ZzVobWxkK0JTZk5oRWJuUmdTaEZpUG1ySkZZCjlmdkdKckFwUGFWUWxYK3FYR1lv
        dXRTbG43WUlGME42RkdZcXlTT2tnOXMKLS0tIGx2MktTM3V0SUNHRXpMR3Zna2Vn
        NHMxa3VJYTF5TXN3SUxybUxCeVg4QVEKNrqK21N7VZ73/+5tgQCYD5YJm11AGkdI
        fToq9ncJ27OLV87frBe5gUA5wE92nfjqdjzHI8etuqZ/KSwIwZVJGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T19:07:49Z"
  mac: ENC[AES256_GCM,data:xyECIbaJqXKwWzXkrPfdsn8/2ZuoFz4gGaL83VumMDeI3alX4CEszqq20g5yZJVXYfmG6gt8CqVcXmoJlNsc0THvQ3kUHCFohPQf6FPbN2j9++keXOu0DWXXfk0zBNnS8qW9o9QELjQW8G0/9yaGaafMczgacbRZScq5hjo0JE4=,iv:SKGq08zVIXeugLHmBHpWGOI9972ZdoJxB/fSXrnJdCQ=,tag:WWpUVqSEFRHwFD12c7QU7A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
