apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  values:
    grafana:
      grafana.ini:
        server:
          root_url: https://grafana.kind.homelab.test
