apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  values:
    grafana:
      route:
        main:
          enabled: true
          hostnames:
            - grafana.kind.homelab.test
          parentRefs:
            - name: external
              namespace: gateway-system
              sectionName: https
    vmsingle:
      route:
        enabled: true
        hostnames:
          - vmsingle.kind.homelab.test
        parentRefs:
          - name: external
            namespace: gateway-system
            sectionName: https
    vmalert:
      route:
        enabled: true
        hostnames:
          - vmalert.kind.homelab.test
        parentRefs:
          - name: external
            namespace: gateway-system
            sectionName: https
    vmagent:
      route:
        enabled: true
        hostnames:
          - vmagent.kind.homelab.test
        parentRefs:
          - name: external
            namespace: gateway-system
            sectionName: https
