apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  values:
    grafana:
      env:
        SSL_CERT_FILE: /etc/pki/cluster/ca-certificates.crt
      extraVolumes:
        - name: cluster-ca-bundle
          configMap:
            name: cluster-ca-bundle
      extraVolumeMounts:
        - name: cluster-ca-bundle
          mountPath: /etc/pki/cluster
          readOnly: true
