apiVersion: v1
kind: PersistentVolume
metadata:
  name: iceshrimp-garage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: iceshrimp-garage
    namespace: iceshrimp
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: iceshrimp
    volumeAttributes:
      mounter: geesefs
      options: "--no-systemd --memory-limit 500 --dir-mode 0777 --file-mode 0666"
    nodeStageSecretRef:
      name: iceshrimp-garage-key
      namespace: iceshrimp
    nodePublishSecretRef:
      name: iceshrimp-garage-key
      namespace: iceshrimp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iceshrimp-garage
spec:
  volumeName: iceshrimp-garage
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
