apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: iceshrimp-garage-nightly
spec:
  policyRef:
    name: iceshrimp-garage
  schedule:
    cron: "H 2 * * *"
    jitter: 30m
    runOnCreate: false
