apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: internal
spec:
  loadBalancerIPs: true
  interfaces:
    - ^eth[0-9]+
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  serviceSelector:
    matchLabels:
      io.cilium/lb-ipam-pool: internal
