apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur
spec:
  interval: 1h
  releaseName: kopiur
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: kopiur
  values:
    logging:
      format: json
    features:
      kopiaUi:
        enabled: true
      credentialProjection:
        enabled: true
    monitoring:
      serviceMonitor:
        enabled: true
      dashboards:
        enabled: true
