apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-media-repo-db
spec:
  instances: 1
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      owner: matrix-media-repo
      database: matrix-media-repo
