apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-s3
spec:
  interval: 1h
  releaseName: csi-s3
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: csi-s3
  values:
    secret:
      create: false
    storageClass:
      create: false
