apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: csi-s3
spec:
  interval: 1h
  url: oci://cr.yandex/crp9ftr22d26age3hulg/yandex-cloud/csi-s3/csi-s3
  ref:
    tag: "0.43.7"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
