---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-controller
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/infrastructure/base/controllers/external-secrets/kustomize
  wait: false
  prune: true
  patches: []
  timeout: 5m
  retryInterval: 2m
  targetNamespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
