apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  values:
    grafana:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.kind.homelab.test
        hosts:
          - grafana.kind.homelab.test
        path: /
        pathType: Prefix
    vmsingle:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.kind.homelab.test
        hosts:
          - vmsingle.kind.homelab.test
        path: /
        pathType: Prefix
    vmalert:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.kind.homelab.test
        hosts:
          - vmalert.kind.homelab.test
        path: /
        pathType: Prefix
    vmagent:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.kind.homelab.test
        hosts:
          - vmagent.kind.homelab.test
        path: /
        pathType: Prefix
