apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  values:
    grafana:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.homelab.internal
        hosts:
          - grafana.homelab.internal
        path: /
        pathType: Prefix
    vmsingle:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.homelab.internal
        hosts:
          - vmsingle.homelab.internal
        path: /
        pathType: Prefix
    vmalert:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.homelab.internal
        hosts:
          - vmalert.homelab.internal
        path: /
        pathType: Prefix
    vmagent:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.homelab.internal
        hosts:
          - vmagent.homelab.internal
        path: /
        pathType: Prefix
