apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: s-ui
spec:
  values:
    ingress:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.homelab.internal
        hosts:
          - host: sui.homelab.internal
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: web
              - path: /sub/
                pathType: Prefix
                service:
                  identifier: main
                  port: sub
