apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
type: Opaque
stringData:
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:8YkZZdKT3CZy,iv:dkartYcn9ZXnnZJyEDAn3qyiBMz5meQqy9NpnjS2ywA=,tag:UwqqnF1L7vesku+ZNRrIcg==,type:str]
  PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:OezrPIy3qddSArBZhotfxkRvH/IRdO/J,iv:jBjQujK1DBZlZAaXtMRFVjAHDMoKcNjGgXBqGCrG/pI=,tag:svdkJlveUOQMF+Ao8yY0qA==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:zqh1R4sQ6dUVY4sA9g/vt9Xz,iv:ti1xwCw4tk4+fM4f/p16MB0aqII5PqgWYlF+mOolNl0=,tag:0x1ljxhkxcQLCrUdTM+73Q==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:kfzwGjTMRQjKguxuJtEQ8cotdHIYYuXkoHlGj4GbQqTXUvDid/JE14VumQdtO5Jimvjx1dl/0l58IF7rANVlha2N0u1XTl+7cABCTkGGm8esyU1JbqI=,iv:EMFxkgLcJnc5WM50bxo/OjVDOGXQJJSvYqbcW3Two4Y=,tag:icvQRWQEbq2eaa0NFYwbbQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM0lWS3RzMW1Jb00rR1NL
        UXY0TS8wYVZSem1UMFhyWi8zMmVTdWxEcjNFCmJRVHg3NjhmdnZHTDZXOVJGWlY1
        WG0yd2NlQzZ4OGI1TEdaTktWV09idGMKLS0tIE9yYWp3MXNZNjEvTzhyblQvK0Ro
        Q0dQMjlwUmdRUFRDcERDZFZZM2krbXMKMIw9+LbuJVYyOEO7qi31byJdUx7obpkC
        sCKC7bDFd1jlbNV+R/nZe0oAgwdfHkiinpdEjvGIeS8BZgRYyu4POQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-17T09:11:43Z"
  mac: ENC[AES256_GCM,data:1C2nk1hwVfbnyujBSsUAKreDoXhxdjK+2iqTi1EVCPy6clZUzJgO7IEdMYanQa7Mt462qk7mP20k2bNprCJQ4wc+UMI9PV3TZl9M0vib5VmLLN1rYFTq8FuQlKansS5PaME3egPwmgd/7fHKARikFwwG3GGUnRMiO3HNnsoNMs0=,iv:D6Ef4wzoJykppCteMBNDBuKisl8qGEuxX7XegwV0tYU=,tag:Yn1mHqDhAh2DA1MIk1Dmlw==,type:str]
  version: 3.13.3
