apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
type: Opaque
stringData:
  GROQ_API_KEY: ENC[AES256_GCM,data:LSE5R0MmanWFt8JmT9M+owGogZkUllc+OkUbVpLly1ghYDXBRP4Klowfyu12UQzTTbXOMMZKm8o=,iv:gfkbtfxs60lVsqnjPUQbszR9LD6A5SrkYgIs+5xTUTs=,tag:c3CBKr+dO3dimU9rbdSItQ==,type:str]
  GEMINI_API_KEY: ENC[AES256_GCM,data:Rgt+qLw4QUM/2ZcE78eXyOA/g1Gyi1qDkXgXveH8D1qsVGEFepWhWcjjbqbc0b4suFjvBv4=,iv:gt+j+f9nlf1Xqai7ygDUP2qLkuBr0jG8Z0fJY1qWe9o=,tag:/hsTlpNenM4f9Y5PllD67w==,type:str]
  COHERE_API_KEY: ENC[AES256_GCM,data:Dpv+nhpejaXAw/RQDgxlIPCl7nBGLF9mQyxfGbcz6nTmbdbG4bYDIrCCaXnjnF7f6Dgyu9A=,iv:4139WhnNWtisIdYAHClV4AmRlY64iHc6x3ZGWhK6Ahc=,tag:erVG6yH6jwLe9hCZcqcZjA==,type:str]
  OPENROUTER_API_KEY: ENC[AES256_GCM,data:9njbzMMrEF35Qt2Fgq2Q8HFrDYCBV7/6lvS/tQb3AEiMwnRo5eRGqsLoRf2sl4djSBBs5o1Vus97DBdOhNU5LMlRJH9lhr/jsQ==,iv:EHXqOvku5A4Oxl0p4wG6gwCJ/Fb+9iaVOFG6m5rUMDM=,tag:O5iCiMq+w7zb2N1r0XBKUw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsV2xJMmlocnU1WXQ0UHEy
        WVo2enNIQWZCeHBCMmFlUVdWSTZYOUk5OUVzCmg0UFpDNi9CcXZnOTF5Y0NGeEhH
        QzZXQ280N0FzOVdVa1VpbFVOd3NQWU0KLS0tIER6SE1JTVJ1T0VsOUtrZy9OdkFN
        MGtGTUNndW1FZy9RVTJZczJpZW5QVFEKw47zNuPvPAwNLcE6sr63cJgoACJKdifO
        sMPx+hvOafXh8O4plGYbj9SygHF9UUCs3R+xZkkoKEK9F47ryJHBPA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-31T17:23:32Z"
  mac: ENC[AES256_GCM,data:hau0ciC0FN7a/vlZ2YbqVNT0mpQ/hnaQuN3e/4vDJsGpZR0vx5+CFWjDleYUDZVGqQkQeyAfWuqQNEZhKoOWRXW5H3LAYoYfPmrxm4n5Zvb96jXvQeQshJd69chFzySuH5/FSQyoYxNnn1D5q2a//zYgS7R2ev9SeW2xnYHdiQg=,iv:ELLDo2oAKUWr4IG8VsnrzDPV1UCjsLBJUHmm39tM/xY=,tag:6/gl+4Ldo21881SA7WkN3w==,type:str]
  version: 3.13.3
