apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: home-assistant
spec:
  interval: 1h
  url: oci://codeberg.org/kasefuchs/helm-charts/home-assistant
  ref:
    semver: "0.1.*"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
