apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 1h
  path: ./infrastructure/base/cilium/kustomize
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  targetNamespace: cilium-system
  sourceRef:
    kind: OCIRepository
    name: flux-system
