apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iceshrimp
spec:
  values:
    controllers:
      main:
        initContainers:
          config:
            env:
              ICESHRIMP_S3_ACCESS_URL: http://iceshrimp.web.garage.kind.homelab.test/
              ICESHRIMP_WEB_DOMAIN: shrimp.kind.homelab.test
              ICESHRIMP_ACCOUNT_DOMAIN: shrimp.kind.homelab.test
