apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iceshrimp
spec:
  values:
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.kind.homelab.test
        hosts:
          - host: shrimp.kind.homelab.test
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
