---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seaweedfs-service
  namespace: flux-system
spec:
  patches:
    - target:
        group: helm.toolkit.fluxcd.io
        kind: HelmRelease
        name: seaweedfs
      # language="yaml"
      patch: |-
        - op: add
          path: /spec/values/s3/domainName
          value:
            name: s3.kasefuchs.net
        - op: add
          path: /spec/values/s3/ingress
          value:
            enabled: true
            className: traefik
            host: s3.kasefuchs.net
            path: /
            pathType: Prefix
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              external-dns.alpha.kubernetes.io/target: 85.208.85.159
            tls:
              - hosts:
                  - s3.kasefuchs.net
                secretName: seaweedfs-s3-tls
