apiVersion: v1
kind: Secret
metadata:
  name: kopiur-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:EvN2ZbBhZR4pKbl4,iv:NAP1MlTkJFx1PyxGSs+VygmFuduZ4VUuQGnWIeChNkE=,tag:jPMjGEHFfZrgHLlCS/VF7A==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:XSUmkoYfB7KMKXcp,iv:6TFOv+C/XnPzIccxHk/o09wQ/lwBhcmVPSvZdvntxbw=,tag:pWTsq60nNzYyN5XZAetVJQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DJ4dA1NmlFDSHYjSrk+WVuzWgsjOdwbWvZEHmQ==,iv:BD52YsEeXPYNtZpA/TNNUpDIq9QNZycZqWgZXnsO/OU=,tag:Jnnwyhp2TeJfuq88a1uFbQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRTRrT3cxbGN0Z0pVUzZo
        amZXK3BZMEs3RTkvcmYwb2lmUFM5Rk00R0cwClJBWHhrbXJhb1hROTZnRXpwZVFu
        aERrQU1QOHYzckp0cVYweGlrdEw2WncKLS0tIDJlMGxWczVVdFlTa2FrbDFvcFBn
        MXkvQTYyRFd6dEFoWjR0eldTeUlvbEUKeabCkcHGmrxEW4qDQO9jJfgrhGK6Qi1T
        xvJkD22Gy2dlcEVMYEFDzOx5nR5He0A4RrO3swWF3OnzGDPAF2WQrA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age194uq3r4zu3kjllp8x947yjk0h0hj33v82qwyged2hczzywrc0spsw9vxer
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T22:22:23Z"
  mac: ENC[AES256_GCM,data:+wvcF/ABnASOK6OYCb7h3X+UprzUXsQ6dElgOHK8ew0u3bSl7P63YWtmX9FELbQLP+3P+gfpVcPwe/1NcSFAVkFF+op6nP2o5Q5uaVBjmKcazH8PcDT7Cmeph66KdvMqMccBJuFpWlAa6hctxH6yinS+oFksbk/nwNblVFxpFRk=,iv:CalUa0mBNt6FB8YZnJ8ZLjYjCsnJuy7czIE+vE8Cz5c=,tag:knSK7r/ubAlG0EO5W7ZiBA==,type:str]
  version: 3.13.3
