---
- op: add
  path: /spec/patches/-
  value:
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: woodpecker
    # language="yaml"
    patch: |-
      - op: add
        path: /spec/values/agent/env
        value:
          WOODPECKER_MAX_WORKFLOWS: 3
          WOODPECKER_BACKEND_K8S_VOLUME_SIZE: 5Gi
          WOODPECKER_BACKEND_K8S_STORAGE_CLASS: longhorn-local
          WOODPECKER_BACKEND_K8S_POD_NODE_SELECTOR: |-
            {
              "net.kasefuchs.homelab/placement": "cloud"
            }
      - op: add
        path: /spec/values/agent/persistence
        value:
          size: 128Mi
          storageClass: longhorn-local
