apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/garage/kustomize
  - resources/secret.yaml
patches:
  - path: patches/replication.yaml
  - path: patches/storage.yaml
  - path: patches/ingress.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      name: garage
