apiVersion: v1
kind: Secret
metadata:
  name: matrix-media-repo-secret
type: Opaque
stringData:
  uwuity.floof.fans.key: ENC[AES256_GCM,data:xwWkQDrr6JfZisi73BrV3k78yw5RT57A/u4P3SnIgfyuzDigDtzCP2wQLqKvfkE8I7n1u0MMqXJV+6yT8H1al5CGAK/ItVGKk/7MkDxAk1LXRQsEEmmZTvrbuU90C6B5qIpDnOVQ/PSl7x7r18zElRQX034F8zAO4BMQPOd1t1dFrwPeCV0uG+J6RMjgkHGN,iv:NOEiMOesAJOJVXk35LC/Tc9UIScmGP1jvFSl8rIcAYk=,tag:2CVqhHyxen8E9CSRqc2z5g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TC9jUjVQeGsxWGtiNTdN
        KzZaU1RBQXd4b3ZhU1kzWDF2U0NTdGk1RkNvCklmVkpLODJkWFpHYXNQU0ZLZkdx
        ODNDaFNaZTZNS0s3b2kvcTZFQ0xWcTgKLS0tIGl5SG1uYTlwVFJ2VUxwcmtDRTJl
        bHNpK05HWFkxV3M3UWJJREtPa0kvczQK/KvE+1PSSQDciAKR2YAvFTzctLC5Q9iu
        i4r1cFY40xMJBk58+RKqzux7VZFs4sQWrrjsSwfyiYZtom3M44vkbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-05T16:54:56Z"
  mac: ENC[AES256_GCM,data:uI7r7t8TMSTF4ejubuqVlqZf/rvvIBbXI1wxXttod1tclMDW7golXYpDiIN/xK+BA/aAcr2XgW+GSbOZfir+5T+tjqNy8hI4NL3nYoHdRB1ldsViUvqjeSzqXiXBDh/ixa8tHibCseUcrxKscXyXNjFkPF+WqfPiiTE1inv9Neo=,iv:zaE8LVDYV2vflRo5Uek2esAjsOK49FhkIhjaqcOH4TQ=,tag:aQYML8fW5z+jHRQJRNOupw==,type:str]
  version: 3.13.3
