apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-controller
  namespace: flux-system
spec:
  path: infrastructure/base/longhorn/controller
  wait: true
  prune: true
  timeout: 10m
  interval: 1h
  retryInterval: 2m
  targetNamespace: longhorn-system
  sourceRef:
    kind: OCIRepository
    name: flux-system
  dependsOn:
    - name: cilium-controller
