apiVersion: kopiur.home-operations.com/v1alpha1
kind: Restore
metadata:
  name: ${NAME}
spec:
  source:
    fromPolicy:
      name: ${NAME}
      offset: 0
  target:
    populator: {}
  policy:
    onMissingSnapshot: Continue
  credentialProjection:
    enabled: true
