apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gotosocial-db
spec:
  storage:
    size: 1Gi
---
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: gotosocial-garage-bucket
spec:
  quotas:
    maxSize: 1Gi
