ARG DISTRO_TAG=trixie

FROM debian:${DISTRO_TAG}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update --assume-yes && \
    apt-get install --assume-yes --no-install-recommends adduser python3 python3-pip sudo iproute2 unzip && \
    apt-get clean --assume-yes
