---
k3s_server_config:
  disable: "{{ k3s_server_config_disable }}"

  node-ip: 10.45.0.33
  node-external-ip: 192.168.1.10
  advertise-address: 10.45.0.33

  tls-san:
    - 192.168.1.10

  node-label:
    - net.kasefuchs.homelab/region=cis
    - net.kasefuchs.homelab/placement=home
    - net.kasefuchs.homelab/backup-store=true

  flannel-iface: awg0
