---
amneziawg_config_interface:
  Address: 10.45.8.10/16
  ListenPort: 49006
  PrivateKey: "{{ amneziawg_config_private_key }}"

amneziawg_config_peers:
  # silky
  - PublicKey: "{{ amneziawg_config_public_keys.silky }}"
    PresharedKey: "{{ amneziawg_config_preshared_keys.silky }}"
    Endpoint: silky.kasefuchs.net:49006
    AllowedIPs: 10.45.4.10/32, 10.45.0.10/32
