---
k3s_agent_config:
  node-ip: 10.45.0.65
  node-external-ip: 57.128.251.65

  server: https://10.45.0.33:6443
  token: "{{ k3s_agent_config_token }}"

  node-label:
    - net.kasefuchs.homelab/region=eu
    - net.kasefuchs.homelab/placement=cloud

  flannel-iface: awg0
