apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/instance.yaml
components:
  - ../../../../components/namespace
  - ../../../../components/cnpg
  - ../../../../components/garage
patches:
  - path: patches/namespace.yaml
