apiVersion: v1
kind: PersistentVolume
metadata:
  name: pocket-id-garage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: pocket-id-garage
    namespace: pocket-id-operator-system
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: pocket-id
    volumeAttributes:
      mounter: geesefs
      options: "--no-systemd --memory-limit 500 --dir-mode 0777 --file-mode 0666"
    nodeStageSecretRef:
      name: pocket-id-garage-key
      namespace: pocket-id-operator-system
    nodePublishSecretRef:
      name: pocket-id-garage-key
      namespace: pocket-id-operator-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-garage
spec:
  volumeName: pocket-id-garage
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
