apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
  labels:
    external-secrets.io/store-access-cnpg-system: "true"
    kopiur.home-operations.com/repository-access: "true"
    gateway.networking.k8s.io/route-access-external: "true"
