apiVersion: v1
kind: Secret
metadata:
  name: s-ui-secret
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:4sMzOkYtZJmsmvkAmj7MCOKv9U8VKPzZaVvwyVljy07fl9+o3QK9c6+hb1litA7b1ujXnsSTV2/TeK1951qfUofeKjM1jWhmxTR+PV/UN3l6XHJGMJuBjKIy7Sg3z9jKnBDl4eBvIkSE0Wpd74yg242/1+9LwNe8DZsYw2OzRce2I0ag1rDzuSQTtDhwZlt29SM5mq+1k7WzNhnRCHeSozIoOdsnykRyFxP6rglx5fUk66eFdGSM2ihQoc+fO1SLDYxBcFzZChcZCVQLZhycKvEafeoHt2IfTtaOCNHGms2H3S9gnNGPveC/se4uRwRcHebqx7EGA8B8MM4+/8hQbMtbzpwKao+MtE7sTvKD87osYlF0QI7rTsZfAp56X1sQWRWQdBo5fIS6I5mj7LCSbxqdkChYpOfdvpbkKIV/n4mvnbaZXJwa6g7cPUZgWNJaI4+w+oTGI5N4YsFPWqj2RPl38oDYv5JEeR29TPx/rQ0ZA/UvY1+uL0vt0zYrcz2FmqAT8M2yp21ks+A/kZaDBz2hMQU9kzmBVdDrQ1VBsErHGnFBjtYrX0sUMkEd+X4a8mw15DL03EjzL0a9LtWPsLf0znrTzrLg7h422Afk8Nq5fHqQAG5IiD+yR53fRJ3A,iv:IlrIkUstjLLmMqR1iBemYlpHE7OH3Sc1n6rQ8bXiGZY=,tag:jrgKy71Fto5IJCzdsZpsQg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6R2Z5YnRKdVVRUVhKK09O
        Z0NaWUROSGgvdzRiTkdtd0tuNTdaT1RWQjJvCnpqVkE2WFpMZnZUdVVNNE9Ob2dT
        WFdhbm9WbHpLNnd0YkhTV0hBc1B3VXMKLS0tIC9MVVVJM2VESUVFT3c1Vllhelp4
        eFhSRTJDa3o0ekRPZkNyVUo4emgyUDQKj8sPRPDeuAZekzV+9KhZHGtfi4dG9/oR
        2P166cFOgohnV/i4M3XQew5t1kwDru6CC20ti2FBIVF/a3dqnuNWVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T13:46:30Z"
  mac: ENC[AES256_GCM,data:wNT9+j4/YrGZixId9PNj4S6Ost1b7W+WshfX5ezAbizSm3AKWlPgAxASuy0ooi/eXgMAS5p/8w0WIy2fyS8xhDCDqOL+VFXglbfNTi3v2ZZOLho+oiTB+xMz3tTm0xKuItTDqb8PcR0WZhnJU3Pap+7QpxXD8oIV7kOunkmlCSY=,iv:6H/RhW4mjYSHRhCPJtWsJy1U5VMJNlXXQfPCspA2leA=,tag:2wwHadjXXyhQHkuBsCoQfw==,type:str]
  version: 3.13.3
