apiVersion: v1
kind: Secret
metadata:
  name: s-ui-secret
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:pjeb+9g1E0BpR70wSbLUsTz35iX0XRX44/x88YHSkXNLyE9TjuupeVYgGtxI5yoWcOZc5ta1dFQ+rtiiaRiVP2jNVedctEz4XIFsh4kRPXv833ItrB/75I4/3xufsUwM0ZNJcwHbYPRlaMsnkR/lMrrAhA0be1oBcYCyv8up76dOGkSzFPofav2b2R94Oslyfuhy7b+lfm75l/JVrNoNT5676iGjVwRrjtDvN3gcU8nAO2ZdMhLa+1dUMZRoOz15SZGc+rl9edTCHGKwow2ZT+mT/hZGrZSNhX+3NPeZx0x1d8a2uZuvueUTIp5D/+9qmJKoh2zoWUOOufSMHmtK3HfyIET6NC3aUwQ8/TdgXcuU1CnfMUSYhCuQjFEZsQncTS5r/Yavk7iGrfw7yNJ7H3UUT0isiNcnoDo7CsUN0+wXCa+GIDEYEnhVe8uPJN/q2i6NanIiJgkNEswOP2t0CIRQpqF/6oyMlpnx7rfrcuWlOYX83DeRZZB7izPYIXSiZwF8hQ9alhGRq77FiDwsVs7F4mADfDbpiO5FjCd8O5X/ny4zxzUe2WFpR3uBOnGiizK3cMIBgziY97c7Div35b8Hlc9WL5/K2wdv9JvdcRWRmT2j+FpYTAiKCk9XCi+G,iv:Z/ptsFHrKinVikZEl8CKHVanBkL4B6LFYszwByw829s=,tag:ZwTH4JNmEKb0TgFB/V0IoA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6R2Z5YnRKdVVRUVhKK09O
        Z0NaWUROSGgvdzRiTkdtd0tuNTdaT1RWQjJvCnpqVkE2WFpMZnZUdVVNNE9Ob2dT
        WFdhbm9WbHpLNnd0YkhTV0hBc1B3VXMKLS0tIC9MVVVJM2VESUVFT3c1Vllhelp4
        eFhSRTJDa3o0ekRPZkNyVUo4emgyUDQKj8sPRPDeuAZekzV+9KhZHGtfi4dG9/oR
        2P166cFOgohnV/i4M3XQew5t1kwDru6CC20ti2FBIVF/a3dqnuNWVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T13:57:46Z"
  mac: ENC[AES256_GCM,data:cEun+6uQtXEJ0Vmm5wWWQ14dWiVFR/9RknHtFYBuginVcqvBBGZbDDneoE6srGfK+yAGPjy1OubiF2tgdg7Qj/fs3pf/DWYMt1Wst/gEJitWbgQsy5kiEQyuBLUpEm5lGSyyfguYfRPPq/gdo8qaLVi7+/GMc30UaF0IHvXk1NY=,iv:FVW53tU7La+57YEVfktQcnLdJ7c3x8JCAXBfK6Exnjk=,tag:yxH+lg+Jome7g4BWsISINw==,type:str]
  version: 3.13.3
