apiVersion: v1
kind: Secret
metadata:
  name: s-ui-secret
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:L4I6C7gMLKJK9FfIZyaYS6HeMo3vZNrzSOb3yiGUOcdh+5TVAXyFsH398jBnLHSd8UM0zc5pp7/nArddlQtq+FI0smf0We9Ofgv+0qNuaq4h6PqA28W5BD48ZIqMNxVf8bjpSbUzborB/d6325079n1ecVjgVkGG5RL/nbYXdB7jZv4pBOdlxIRl0A50VC3qVkdd9M1d/Ff2e2lk3tqw74VMnksbtNVPosEmOv6j6U1xTYWFGnfBPmDCNNll0E/D8b6oZKqLxylXMsIBUNqINtPH8SwosesYcHP3CsCOljPIxBLXD3CgouS/6ZGt7iYMoIVcJ1Oaw54MR5DX1ks=,iv:UMcOy//IyHSHoVWTT6Si64CqgrzaFq9vyTgfLR92oo0=,tag:wlJ/0LnbF4wYqKaaga/uzQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6R2Z5YnRKdVVRUVhKK09O
        Z0NaWUROSGgvdzRiTkdtd0tuNTdaT1RWQjJvCnpqVkE2WFpMZnZUdVVNNE9Ob2dT
        WFdhbm9WbHpLNnd0YkhTV0hBc1B3VXMKLS0tIC9MVVVJM2VESUVFT3c1Vllhelp4
        eFhSRTJDa3o0ekRPZkNyVUo4emgyUDQKj8sPRPDeuAZekzV+9KhZHGtfi4dG9/oR
        2P166cFOgohnV/i4M3XQew5t1kwDru6CC20ti2FBIVF/a3dqnuNWVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T15:58:22Z"
  mac: ENC[AES256_GCM,data:QIb3y9P5KCZvxf+lLGTnIXuCcBO8+TJbN6EdbFY2Dq52tSl5y6Np6hN41Db/O/ZYEyGt9RsHv/3ILxWApn4fl+DU+ohjEQ1iTQQ+hMURObIGG6Iz5sLL/TKq/7/wUK26pReddrAxMSUTYd/BGJeauhSsVjPF8Z3em8Cy9DIEsNw=,iv:36vMkWUNJT08w3hDCbOJkQEjVT1cqlw/mSpecRx57c8=,tag:t0GPmDUq/6uM9Uk2zhHQ/A==,type:str]
  version: 3.13.3
