apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: iceshrimp-garage-bucket
spec:
  globalAlias: iceshrimp
  clusterRef:
    name: garage
    namespace: garage
  quotas:
    maxSize: 20Gi
  website:
    enabled: true
