apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  values:
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/target: ingress.homelab.local
          hosts:
            - hubble.homelab.local
