apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/traefik/kustomize
patches:
  - path: patches/service.yaml
  - path: patches/ports.yaml
  - path: patches/dashboard.yaml
