---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/gotosocial
patches:
  - path: patches/domain.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
  - path: patches/ingress.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
