apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: conduwuit
spec:
  values:
    config:
      global:
        allow_federation: true
        allow_registration: true
        new_user_displayname_suffix: "🦊✨"
        server_name: uwuity.floof.fans
        well_known:
          client: https://uwuity.floof.fans
          server: uwuity.floof.fans:443
