apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wakapi
spec:
  values:
    config:
      security:
        disable_local_auth: true
        oidc:
          - name: pocket-id
            display_name: Pocket ID
    controllers:
      main:
        containers:
          main:
            envFrom:
              # TODO: use json patch here!!!!
              - secretRef:
                  name: wakapi-oidc-credentials
