apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  values:
    httproute:
      enabled: true
      hostnames:
        - longhorn.vagari.homelab.test
      parentRefs:
        - name: external
          namespace: gateway-system
          sectionName: https
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
