apiVersion: v1
kind: Secret
metadata:
  name: mautrix-bridge-secret
type: Opaque
stringData:
  APPSERVICE_AS_TOKEN: ENC[AES256_GCM,data:ZVA0d+qztEElwBc4o7zW9F94CWCW/3EtaCZXEmZvMvfP2wpXsou/9VPdOIcluu9T1vsRYh7N/oi8asbh+C6RMw==,iv:/XuYqmPq9H8OxjWnYZfdwNKoaRBG9KITqxf+YKzpeCo=,tag:QyyzOGS2Xj5N78To0O8hIg==,type:str]
  APPSERVICE_HS_TOKEN: ENC[AES256_GCM,data:ePvnm4WcYWtzUrgdXH8Q/z58EK1dCUBUuub23dJLHxaANt58oswsr9/T04AMob3u7XjGJl1UraKILpsRlL1vjQ==,iv:o6uChn8ME79rin569hvfaRx1qfOlCY0N5VDj/0tKRAI=,tag:PnBr1PuL+gDRcpFh+6MTag==,type:str]
  BRIDGE_AVATAR_PROXY_KEY: ENC[AES256_GCM,data:8tKYTWeNIOaCPr6vnz/TB1dtPjCzc2c2mF8Dp5JLcLQ=,iv:7eIEU6KbEJ5JlYOPxooiU6/hGmYlhcjDSm/p0LUs4HU=,tag:3H49IQteNjEfgGobhIVIZQ==,type:str]
  BRIDGE_DOUBLE_PUPPET_AS_TOKEN: ENC[AES256_GCM,data:BvKD+BanBZ5EoD6D9W9LjNxavBiLsrCCCWRQmUMr9oJw4ULVQYNljYc8KbA=,iv:u406mGHfP37HW56uDN5AivZ388EWnUBsBI/Qm6uFBws=,tag:Yz/JZ4zrwHHZg1pxrOfm1A==,type:str]
  BRIDGE_DIRECT_MEDIA_SERVER_KEY: ENC[AES256_GCM,data:Ww0XO+3xr8m2JwgLVOa+hf5H826lWNvGTx4bEcZ2LxR3+a3A7wmG4oWcumUQrhxzG4UD/BCZPGYUsQ==,iv:q2LcBxjwa7XrmZW2/RplmnyTF0mRaLVEk2exZk17I9Q=,tag:fCwj6AH1e2LhaWS3iKvDKw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQlM5ak9YSTNXTVBmZEQw
        Z1NRc2xEdUNMWWtqeVlLeFBvY1ArWXU1MFhJCm1XNWVVZDg2a3lidkdwcGVXUmJj
        SDJ2NzRIWEZsQWp2MXV1NXlEVFIzZVkKLS0tIFFiTEtuMXdLUEF3VzRQdmMzOXJ3
        RW9XVjNVcDMzejBVR1FhUjBXNWVTN1EKgF0trsjXRUS9+QIKCmOohGIfaRMQ8OPL
        mc9n8PY1UNGy+fO3eCwJLhlTopWzhzl7tvly2ywdUjXzPjAfF0/Yag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age194uq3r4zu3kjllp8x947yjk0h0hj33v82qwyged2hczzywrc0spsw9vxer
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T18:49:22Z"
  mac: ENC[AES256_GCM,data:J1ZnT5hX+/MCsdmgrFQvp5PFEnn7lltrAGJp5nCgQ2MFCUrEYSzvv3jJkjoFz8zLv7MoJ9I+Na3pd/kMfYJ9ysKpxdOY7oiOr91Kjjc2X46a6hskejncy3UWb0G9ydLITv5mM+s/zKZDrm2lqld/pat4CDksJmTnd7Pq5v5lhHk=,iv:rzf2OrH0vvWInodI6KUq23r3VEBukKVmKqBjdAyVcZ0=,tag:Nv7WZlRgXe9n0CDlTdCAhg==,type:str]
  version: 3.13.3
