apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  values:
    route:
      hostnames:
        - renovate.kind.homelab.test
    webhook:
      route:
        hostnames:
          - renovate.hook.kind.homelab.test
