apiVersion: v1
kind: Secret
metadata:
  name: s-ui-secret
  namespace: s-ui
  labels:
    reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
  reality_route_match: ENC[AES256_GCM,data:GXeylLcKsJ+PzUh/kQXmk4lIouqczs7TFlbSWt8=,iv:tw+epnpecvj3hYkVsKIMeP/Dq69GXrsrC9sgNvZamNs=,tag:yV1boWwEFsswZS0t3yNH5A==,type:str]
sops:
  age:
    - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQVFVNFoxVG5HR2tIc0pH
        ZWduVm5mU0t1elhpZlJKOEZXTm1HcTR1YjFNCnZnRyt2Q1lKSVM0Z282QTNWdFRS
        YmpzWnFEa2t4YUYySVMxL28wQ1lVY1kKLS0tIGt1ZnpVQThqMWtCVThEZ25MMTdO
        bHNXQjhOLzAzejIxNjVQVm5yOThaVFEK3GuatkF7hVj/Jct6YljRK4mEBu9WgAdm
        XqQCS1lMm7UqWdeOjBtXpeU/b1WbUHRWJpKBvrtaJvdfEadB1zVkXQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRVIvUk1aLzdZUWRoOC9C
        a2dFRG42ODAxT3MwblNnM0dQQ2FnbFNDeVZVCjlVY1NJQlJMOGxBVkZLdUtQcUNj
        dkNTUmlnNUtMOHczQTFKUU5LUzIwdk0KLS0tIE95SWNSVkNWZkU2Szhhb1B5WnhH
        Vm5KN21ZY0JDeGdlVHFtdnpXYitGMlkKyRJ/2DX+sdCbmqvASgza8MRDKwz6r4ht
        yGVagPhcG6bkc4nPyCteBNv4ucEa0JKQ2b6vO1hbBfd6SGpEHRGypQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T08:43:20Z"
  mac: ENC[AES256_GCM,data:h4K7IUc0aX6KiaNJujE0PgpOMD9kwSPvV5UxyTIM0LUjYvP3HGk7c3s+BTlwzrlhxMfz5EHE6MgRl1loeUG6iiqhMT0ll9Q3cU2E3Oi+oeizRd4eNokaGFRwqwf+yaa8MfwL5MYTPTheLfoGKoaywWdkOyawEaNZwKQoPJD8K6M=,iv:1Vcm4hubl2eDI+v1buAgGlrxgwuAYKAUGd4wOsZ20fc=,tag:c/mR0RWsjNNCGSgDM2kI8w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
