amneziawg_config_interface:
  Address: 10.45.240.17/24, fd45:45:45:f0::17/64
  ListenPort: 48092
  PrivateKey: 4GbKGwyeEV4BonYKfljPrttkK1BpfMVJzJ1MkaLFIGI=
amneziawg_config_peers:
  - PublicKey: "{{ amneziawg_config_public_keys.master }}"
    PresharedKey: "{{ amneziawg_config_preshared_keys.worker }}"
    AllowedIPs: 10.45.240.16/32, fd45:45:45:f0::16/128
    Endpoint: master:48092
    PersistentKeepalive: 25
