amneziawg_config_interface:
  Address: 10.45.240.2/24, fd45:45:45:f0::2/64
  ListenPort: 48092
  PrivateKey: 4GbKGwyeEV4BonYKfljPrttkK1BpfMVJzJ1MkaLFIGI=
amneziawg_config_peers:
  - PublicKey: "{{ amneziawg_config_public_keys.master }}"
    PresharedKey: "{{ amneziawg_config_preshared_keys.worker }}"
    AllowedIPs: 10.45.240.1/32, fd45:45:45:f0::1/128
    Endpoint: master:48092
    PersistentKeepalive: 25
