apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: garage
spec:
  from:
    - kind: GarageKey
      namespace: pocket-id-operator-system
    - kind: GarageBucket
      namespace: pocket-id-operator-system
    - kind: GarageKey
      namespace: iceshrimp
    - kind: GarageBucket
      namespace: iceshrimp
    - kind: GarageKey
      namespace: matrix-media-repo
    - kind: GarageBucket
      namespace: matrix-media-repo
    - kind: GarageKey
      namespace: gotosocial
    - kind: GarageBucket
      namespace: gotosocial
    - kind: GarageKey
      namespace: nextcloud
    - kind: GarageBucket
      namespace: nextcloud
