apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gotosocial
spec:
  values:
    route:
      main:
        hostnames:
          - social.floof.fans
      apex:
        enabled: true
        hostnames:
          - floof.fans
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: ListenerSet
            name: external
            namespace: gateway-system
        rules:
          - matches:
              - path:
                  type: Exact
                  value: /.well-known/webfinger
              - path:
                  type: Exact
                  value: /.well-known/host-meta
              - path:
                  type: Exact
                  value: /.well-known/nodeinfo
            backendRefs:
              - identifier: main
