apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/vikunja/app
components:
  - ../../../base/vikunja/app/components/oidc
  - ../../../../components/cnpg/components/backup
patches:
  - path: patches/oidc.yaml
  - path: patches/route.yaml
  - path: patches/config.yaml
