apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/matrix-media-repo
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      name: matrix-media-repo-app
    patch: |-
      - op: replace
        path: /spec/path
        value: apps/kind/matrix-media-repo/app
