apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/iceshrimp/app
components:
  - ../../../../components/cnpg/components/backup
patches:
  - path: patches/config.yaml
  - path: patches/route.yaml
  - path: patches/storage.yaml
  - path: patches/placement.yaml
