apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
type: Opaque
stringData:
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:+BGV6nMnFYOa,iv:inizJdQQTEjM2DKLzqY8fh3LsUMi2jUdgsrrmSi89pw=,tag:MGfHfpF2lLRxRchgPME+FA==,type:str]
  PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:qGxWav1ptsDPa+SNZ+i1gUnSdKReyCcm0yNm,iv:ccF3nxoUKvU/tGqgGl1rliowQgH/3i/5cyLNzKDaxbc=,tag:F9gWs495nnqC1J9Y7WjcDA==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:qH7dXTz8yQUnAoTw,iv:9tNR/5DT3XXIrCHPrCoWaeWL6NZ/2hkMlLmqJESJu9I=,tag:a8hecuWRWly8iy9wl7DgHQ==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:uuuAeK54sqxaR1fjfxtYv3NObt39fnjQi5pAKl24/Gm2w7gEac2bEZBS0oewt1vaZOX7wwKZXij2RjSDrdOcD4ay8LYx4XTJ0vWc7umKUzaqNlq5LcQ=,iv:hynt+gDPY3DAujBgewVbPspMj43IfVzDfNQ/PTH7Xlo=,tag:ruz4TB2bTy/bl0CL2euDOA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUGNXeXZRVUJZdTBJamc4
        a2h5T2hYWkJpa1Fnak1BelN3YlhaeXB1eFI4CllBQzFRdC9FQmVNUHVlemI2T3V2
        L1lFaUtzQi93MFZRNmsrTGRQcnVKSVUKLS0tIFc0MUV1NmNuQUZBa2ZUTDZzUWxv
        RnB1OHNJck43dzVVUWhzaEFlb1p6QUEKCPICg6CVNv3m1PmCf4+I+1nGz21qsUuH
        XEF2yAtND6baJUieAbFEH8wReOfIensismyX70RDO0UWke/ikMMm0Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age194uq3r4zu3kjllp8x947yjk0h0hj33v82qwyged2hczzywrc0spsw9vxer
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-17T16:53:45Z"
  mac: ENC[AES256_GCM,data:rg8h/se7JU6Rj+My8GWeQvGwcKMQIbMi/iV3MdWXLOIPfAlPwrJy4+OY8igKcWo/NpwWWgNpwNM3Iln1UVJt0yY6BS6y6ST5T7EQ9aPP/o/OODSOHlRyvPRDdZvvcRZAzA9kIOhFXF/59IH/M6xrflMgaAkyva57MS+h44JUONA=,iv:q0xlMb6r0hnLW5eQS7rHQ1YIbLg2xGZk7s1n7TCv0SY=,tag:BaNW/xy4kb0j+MxynYQqxQ==,type:str]
  version: 3.13.3
