apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/pocket-id-operator
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      name: pocket-id-operator-config
    patch: |-
      - op: replace
        path: /spec/path
        value: infrastructure/production/pocket-id-operator/config
