apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gotosocial
spec:
  values:
    config:
      host: social.vagari.homelab.test
      protocol: http
      advanced-rate-limit-requests: 0
      storage-s3-redirect-url: https://gotosocial.web.garage.vagari.homelab.test
      storage-s3-proxy: false
