amneziawg_config_interface_host:
  Address: 10.45.16.16/24, fd45:45:45:10::16/64
  ListenPort: 48111
  PrivateKey: "{{ amneziawg_config_private_key }}"
amneziawg_config_peers:
  # esmae
  - PublicKey: "{{ amneziawg_config_public_keys.esmae }}"
    PresharedKey: "{{ amneziawg_config_preshared_keys.esmae }}"
    AllowedIPs: 10.45.0.0/16, fd45:45:45::/48
    Endpoint: 192.168.1.1:48769
    PersistentKeepalive: 25
