apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  values:
    web:
      ingress:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.homelab.internal
        hosts:
          - host: flux.homelab.internal
            paths:
              - path: /
                pathType: Prefix
