apiVersion: v1
kind: Secret
metadata:
  name: x-ui-usque-secret
  namespace: x-ui
  labels:
    reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
  config.json: ENC[AES256_GCM,data:ld/Bn9esiIa72VOweNv7TQkE5JVbHo55j73QTzW4wU/EeE4dCFlkouXyyuRNK2pd+3qQGdKzlwyJN94+tHbED3UDx2Bmsb+cNidHsXrMTz49cYhtgfc604mnMissMF3pBC4ZkrXCOWmlE49aD+zSJ5/EjFL5c/YLrD5SydGIDWNC4rGYoEVmpBLbTzl4oipJtjsjtor6Tp4haVI8vpsyluQmk7JDF6SLK/5RcCEOw5CzgdjzLEF4Sse3wT9D0PUEQ7WiFFomCRp7rdn6cJo5zly/r1325nf+aKpE3sC+ka+0r4kuW3ZitLSY+6+HqIDUqV5PNrprWZe+kyQ6lwxPJy8Mv78fvmf8iWcS1M83sr3k5CBq4XtQFiqNU2mskK2o2rYJOa4ORc2b9AVr8gQKuL7f2HFe5naBjitnzMeHtVv5wAUhyQka1CU44nSHXoK9BaNWgT0R2VsCTKCbc4xBCscJm4LKsPuznrs5gupkFddUSneEczfScXV7C1+S8QSN52xLYGXB0htn0AKZ5XF+aGCPiVonhw82bG6dR3n4/KMEdw30LT3sp7h0Q4QBTX3q4HpFGQJiYduHD3JY8itVvIIbwOACZ3KtrJqjiPAyxA+pq2y7dgjkCTop7Vtzhq8yxrWDmpSh16ctjwZkcGUDlvywUhUsFlmuIiPRKDW1c90An3Ph8xP8BmOVzHs0pDXFC1t2f3A9Xs6TMeyVP6D+qGwPGaGNtjsgoXN2jKM5RyhvMCK3Az+7ZScXClkFWD++Wawl69tkXmQfIGnWKmyKpvkD+JREfSzkbqqdVTv5e6Koa+ljtdxEXqOIHu0y2NdPdUqLx460LnxAAx6xuiIQj3uA1G+ZkJvPm8F+dJbKGWYcZ96YhRVfnVSivgNbh96xnFeUcOLkvfz+f4BSjMIweivFgA==,iv:fIa2CcMgc+mACycK/1ejYeojGEAD9BOZdaUshMkhSKI=,tag:sX4XF6rXI8K7XhpC0OL7MQ==,type:str]
sops:
  age:
    - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVUlTc3IzS0hGWER6UVBQ
        Y20wd1dFdXNESFg5S0ZsR2RtOElYVmpZQVh3CmY0S0ZDK2YrWDRXMjBxcXRaeFdC
        UTB0bitlQUJ6MEhmNUc0d0R4R2pETzgKLS0tIGZTTDZrQTVPdnR1TTNZVXFOTXJw
        TWhBMVU2Z1lZODlSMll3TzdwTDdzNncKY1GQdd3Mt2QuEaJEE3lycTpdUQffssXo
        6ex+F3KmAm3yrX2y5XOXcVJlYVYFYs/n1GYdL50wQRBb7Taq61A9uw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaEFTL1lxaTcxajZEL3Fy
        NEdwTEdWM0NZNHp5TWhnbFdHTnZjMW9qWnk0CmgxcE1uRkpMQUROcUM1WFNEZ3h4
        UlFEeXFrSkduM1pzbDkrTTFodlZyVEUKLS0tIHB6L3hFQlJ6VVduanJXTTI0YzhT
        Qks1dmdyU3M4TEhoZGIwb0p5MzRsck0KbcA8KcZpT7JVTPE1SRMZp1Wrktl01anh
        WDwDFNWuJvWNRovhfT8TBL0tvWtNucJCrE1UO1ytKQeFWfhSvWAGMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T17:02:53Z"
  mac: ENC[AES256_GCM,data:mpOhBwdA64lhAxfsY+Z2dyNyh3phiandufX0laJWmpjEk10iVWZb9LyYqtkLcHSb9AaeP9tXyEKndrnaJ5IHSvb4JKFkMlxTL7m200zlQVvVGq0eZ0+upz3q1Edsro27DHtdwnQZQxlCIPTH8xwhZw4GmttUCnxcsH37M80zXT4=,iv:+8Vf7pQkP2JYok+7CF5+S5N5gcjCIL5iguI6v7ZZxS0=,tag:h2fV4kIQfITXlIEaIBPIUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.1
