apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-controller
  namespace: flux-system
spec:
  path: infrastructure/base/victoria-metrics/controller
  wait: true
  prune: true
  timeout: 10m
  interval: 1h
  retryInterval: 2m
  targetNamespace: victoria-metrics
  sourceRef:
    kind: OCIRepository
    name: flux-system
  dependsOn:
    - name: cilium-controller
