apiVersion: v1
kind: Secret
metadata:
  name: kusai-mastodon-secret
type: Opaque
stringData:
  KUSAI_MASTODON_USERS__HOUL__INSTANCE__ACCESS_TOKEN: ENC[AES256_GCM,data:ynBCCKYtNdKuDKqTZg4cIK2/b5aOUHxIQUFIjDqWY1M=,iv:+Trd5NJnvqmYxzvkvL0NvpHOcKJ2pWVYNaho7fEnJA8=,tag:PQ9T/nb/CS96qUdT0mdzxQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMzFCQUs5YnBJVEZ1eExn
        YkpUUy8yWkVqc3lwSDR2bWpwemFUc3RwWFNjCkFSRjJTWHI4L1Z4Sm1qUzNZVVc1
        aW11N3R5TUZpL3ZhVWc3Sllia2tEOVUKLS0tIFJTcUxQSFEwVmZBbVNMRkhQMk9J
        KzFoaUFxZitkMXdPRGc1eGl6NWdHNEkKUwElZK3VTzIXNRxpLkeTVKOTmCoOE3wx
        VQWp7fRN8I8wBEKzfPQZRrEb0l9ylpqpsJ1Zoq2DtqsWHD1bHmpdRg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T14:16:39Z"
  mac: ENC[AES256_GCM,data:oR+sKbDEdB20vFjbfvHUrp+u8CCIXlMw4uKWlVwQB8jI3gFeqrBLcjPFYNRnymCWckWhJWPCftT0ZlZ7NdzbYEwePCZAIR7/Lrgsfk8/c6KL4Op/ZI50wNn5kJ/Ojhlqsa7zf8HPgZl2Mn5H8eb7ijXdzUQ4QwuEqQpbIbyZiV0=,iv:8mUH9d4OeUbm+EdoZGXSZg1tjOx+wT4st+hyel5dYfk=,tag:Hn//yhWnSX1WSDaJ7tzcWg==,type:str]
  version: 3.13.3
