apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: garage
spec:
  to:
    - kind: GarageCluster
      name: garage
  from:
    - kind: GarageKey
      namespaceSelector:
        matchLabels:
          garage.rajsingh.info/cluster-access: "true"
    - kind: GarageBucket
      namespaceSelector:
        matchLabels:
          garage.rajsingh.info/cluster-access: "true"
