apiVersion: v1
kind: Secret
metadata:
  name: kopiur-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: no-one-cares
  AWS_ACCESS_KEY_ID: nobody-cares
  AWS_SECRET_ACCESS_KEY: definitely-not-a-real-secret
