apiVersion: v1
kind: Secret
metadata:
  name: kopiur-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:fqUnv7Osx4utjJ0n,iv:KX2uvvbn0VtWDHYgaQTvYKeaik93sQjRpoIUyWGHlkQ=,tag:cYOalP9Rh+Fo86KMG5L7VA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:i8gxY2f+7FoZlIxB,iv:19y8h0s1KXh12OztpYWwadYC9Bh5MzNTnoKWNU1NW8Q=,tag:HxAVFVW4lsZ8FGamicMhqg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dMTND2p7/apT9TLiT2W+udCn85cA5Pr9Tuxfkw==,iv:mwGO5jEtwKZCCp2nlGVTO5Y+o5UxjCIB3Pv89YUYZkk=,tag:gkRyuJYUHOFO96thgvijMw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYmRwbUJDaGN5S3JTS3VF
        NXptS1ZOMlYwWFV2NHErbmQ3UXRZTjZteDBjCmVQV1NFTkhWSzJhNEducEtsNGxW
        NXBLaGo4TWxLWWNodS93eG12ZjZUM2sKLS0tIEZaaGR2MWE0SFJtQTdCcjZ6cnds
        VFEvdVR5blhlNEovZDRqWlcvY054SzAKQB3ARh0K7zIPDNRMxmB3hoshsJQkVIZy
        prhOUTmR00sGgTk3c5ZPEo7r2EdLPfzD7YWTfseLYjuqicGkYsWwNg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tfa0m86eq3r4putn2dn8ddswexj6k6mawjwxcqtauqr5792jtujqxtpwn9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T22:22:39Z"
  mac: ENC[AES256_GCM,data:6mshgfscK5Du3ehB3gPdcBQhjdqkHb6IpB3vCIPFapVerUiphgyku5epRkGMr8DFvSTMJQSolmrs5u9S/JiPPlFbWRkqjo4LOVkTAu7n/9sm/tfx5ApCQ2NTIr6hrfV4e5MAxiEy5649LSMfHDym8/bxcf3R5GDa3yIG+cqsKfs=,iv:ZvKxssLZ3QR05haHL1ThFjhvJniBmw9fcy/vvKntMvs=,tag:9oiJQfUwQ0E7SuSjPi7wQQ==,type:str]
  version: 3.13.3
