apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
type: Opaque
stringData:
  nextcloud-username: ENC[AES256_GCM,data:gXqBaak=,iv:3M2+NM61idj6x8ihIGGtJW1WEhlGRi04f1x7uE5cskY=,tag:8ISSSdzx+8D0ZGto2OJyiA==,type:str]
  nextcloud-password: ENC[AES256_GCM,data:ySMOMmccS1ltq6tg,iv:iYynZReD9JNa8XedWlyUan7UXa5fVQ2nb+do0CC0rrk=,tag:8WNvfVO0Qmo7kjDWweNfPQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWFlhdlZNM1JSNm9ONDd5
        OU85SnQ2eEJBUFB5elMwUmpEN2VwdWdOY2lzCm5PeDZzelBQL0xOQmxHQzFvaGll
        WVloZXpTSTV6UzdUTEVJSElMbVNrMFUKLS0tIFBVckVHd0RQYkVaQWJtVjU1eDNj
        RHUvWGIwQWJ0clhQM2tCNDJnKzMwZEUKXHp5CVObyW5dDtk1J35MmwaKjQDSGFPz
        0BaVu3vycLHPoIzVKLcErkK3/GRw3r1qvBZmAKdApTeYWjeBfFIrrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tfa0m86eq3r4putn2dn8ddswexj6k6mawjwxcqtauqr5792jtujqxtpwn9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-03T16:21:14Z"
  mac: ENC[AES256_GCM,data:2jpR4KQmXCZBciJHhIKxYUhphisI9sJbfnCc+STEJRzpNGLfHCQemABHw+j/bSTkcWfYGI+fgjalW8NaFfNfQI54B0hh5If/pbw1pjhIqKCJdbDOuhqNqwARYvrh0h1UefEifPBxR9Gswz1WiKwkBauffE8CgQr4yzDXb7x378Q=,iv:wF3dn24YC8okJG7yjSiqYKfBpAy8o09JCq3gU/TWBVo=,tag:vFZxEVwRBV057G7CsE+/Yw==,type:str]
  version: 3.13.3
