apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iceshrimp
spec:
  values:
    config:
      Instance:
        WebDomain: shrimp.kind.homelab.test
        AccountDomain: shrimp.kind.homelab.test
      Storage:
        ObjectStorage:
          AccessUrl: http://iceshrimp.web.garage.kind.homelab.test/
      # Allow private Storage::ObjectStorage AccessUrl endpoint
      Security:
        AllowLocalIPv4: true
        AllowLocalIPv6: true
