apiVersion: v1
kind: Secret
metadata:
  name: kopiur-secret
type: Opaque
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:ukMJHubtj3gnMs/Duzg4k5obQEvaw06b6mHzh/r+sYMQ1MtE/an6QuYytnCLwJHGuVXdVaUzHTpBCJrbA01S+Q==,iv:ZHfFcgDwwbe4Thv7NRKKKw1nwCDw9wfx9NLrqJf+x+U=,tag:EazbbfyKbOvutW7FuKuQZA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sRWpZKmwUS4uvSPIQF9E/71bWbwue93D2W1WhEL1YPJmS+NVirTk4yQA2vhRakoscC3eCUAug3eLdy73sdx2vFVvt97Z,iv:/17AWzg6XByjCGhHmKGVUK2nwfIrw8r1L/JXUYmGTFU=,tag:UrSytrxavKcDVxJOPv1g6Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:q50egwCn4y9puyjTJdi8hiZXDBJmCgW7JmOAJcjlvbk=,iv:+yxs3H3Enruh+ID2jGYef2X09b5Li2bFjZfbqkHlVNA=,tag:4VWDEOPyREZPbCjqUGWU4w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhN0pIVjRIUi9uTU83NE1j
        ZXEvYVBSRm1IMEwyVWZXemQwbVN0SGhBWFJRCmxwSnFFeTM1TzNGOVI3Y000OFZS
        RG4zWks0UHNkRkFoa0ZoN0d6RWF3VkEKLS0tIG0yV3RuRU5CZXVkL0I1RFNvMHdj
        cEx6TlFLZENlbER3WG5zUTA1ZlZ1cVkKqRsqlLjYiB3URr7ViOYsVMTDls4zZUXN
        6p056RNzNKzhmcgYelos0KQcXhWEtWUHkPQ7RJ8JRBDMsss+e6HQYA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T21:35:45Z"
  mac: ENC[AES256_GCM,data:rIWpQdKzJp3VHXl6JctvirujFdlt+iqsWIDharDL8UsjSob98L5x3I9ipr4wyybXPwhnKGopNJTyiFdAudkrGjIuXxL5IMAAHsu3uU9702X3uAQWJRSXeL7Cr4kIsdok2FLm6ACATH2+VKH3pK5K4+9/PWVOlCLnN9X3Fwaoscs=,iv:WwbMeVr15NgHmeRKafdyKMgV+oHjEwWSGeGK5/B5ev0=,tag:tzPnQ5NZrsP3i8sv7QDe3A==,type:str]
  version: 3.13.3
