# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager-controller
spec:
  path: infrastructure/base/trust-manager/controller
  wait: true
  prune: true
  timeout: 10m
  interval: 1h
  retryInterval: 2m
  targetNamespace: &namespace cert-manager
  sourceRef:
    kind: OCIRepository
    name: flux-system
  dependsOn:
    - name: cert-manager-controller
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      NAME: trust-manager
      NAMESPACE: *namespace
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: trust-manager-config
spec:
  path: infrastructure/base/trust-manager/config
  wait: true
  prune: true
  timeout: 10m
  interval: 1h
  retryInterval: 2m
  targetNamespace: &namespace cert-manager
  sourceRef:
    kind: OCIRepository
    name: flux-system
  dependsOn:
    - name: trust-manager-controller
    - name: cert-manager-config
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      NAME: trust-manager
      NAMESPACE: *namespace
