apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
spec:
  values:
    coder:
      ingress:
        enable: true
        host: coder.kind.homelab.test
        wildcardHost: "*.coder.kind.homelab.test"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.kind.homelab.test
