apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
spec:
  values:
    coder:
      ingress:
        enable: true
        host: coder.homelab.internal
        wildcardHost: "*.coder.homelab.internal"
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.homelab.internal
