apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: garage
spec:
  from:
    - kind: GarageKey
      namespace: iceshrimp
    - kind: GarageBucket
      namespace: iceshrimp
