apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-secret
type: Opaque
stringData:
  encryption-key: ENC[AES256_GCM,data:W57aXMqQQ42GYwUZg7EDzK/HP1TeO97cu3n0X0dUSh56I5XAJBB1zwqx9cs=,iv:QAzSu9K1mJ5v4EgmRwH9o5xAHOKPg3B4cc35NeAcR1A=,tag:tN8pXyjhkWr5s7Ms9TVSUA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QmtJOFh5dTIzMGwxeUJv
        SmNSazcvRGljUUYyN2p4OEY2bU1zcTdhVjM4CmZ3ODNhOVg0cUxUS3dhWmZkVHFG
        Nm5LVlZHNVA4eTRZelRRaUFwQjJRLzQKLS0tIGFmTFdWeVArUmt2bkd2MU1tMXBp
        WnZvb0RqVnhmekdnbDNUdDBBajVrTVEKz/3zJvzGeEtTQHg1U/sA/NkYalJ8HynC
        DNWqE8aAqfVNPiUvs01IQT4pxpAlhyRP0MA+El6ZGbrqKP+KlosQdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tfa0m86eq3r4putn2dn8ddswexj6k6mawjwxcqtauqr5792jtujqxtpwn9
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-18T11:08:56Z"
  mac: ENC[AES256_GCM,data:GQGO9VFbzK95MKo6wtOLxeua6HjHz/MHkOb6xDCtJ9w6TJLgy/GSOOuwgFd8rN7E0ZJKgZ+xCf4uumzvwA9fYhXKqqT6ulxBwajx0LsYI37Wbnf71GXIZcRjrKnl3zZZmwNm8hoRwt+1pUorWwjGTT5tcV9VWfE5Lg89BoIwy1c=,iv:N3GXV9fjKTOOwS5R2NdYUiHPLtaZ0pR7SD9l5ZJpZTs=,tag:OZqSkr29RH96nAC6N58g8g==,type:str]
  version: 3.13.3
