apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: gotosocial-garage-key
spec:
  clusterRef:
    name: garage
    namespace: garage
  bucketPermissions:
    - bucketRef: gotosocial-garage-bucket
      read: true
      write: true
