apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: gotosocial-garage-bucket
spec:
  globalAlias: gotosocial
  clusterRef:
    name: garage
    namespace: garage
  quotas:
    maxSize: 20Gi
  website:
    enabled: true
