apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/garage-operator
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      name: garage-operator-config
    patch: |-
      - op: replace
        path: /spec/path
        value: infrastructure/kind/garage-operator/config
  - target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      name: garage-operator-backup
    patch: |-
      - op: replace
        path: /spec/path
        value: infrastructure/kind/garage-operator/backup
