apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: pocket-id-garage-bucket
spec:
  globalAlias: pocket-id
  clusterRef:
    name: garage
    namespace: garage-system
  quotas:
    maxSize: 5Gi
