apiVersion: pocketid.internal/v1alpha1
kind: PocketIDInstance
metadata:
  name: pocket-id
spec:
  persistence:
    enabled: false
  logging:
    json: true
  metrics:
    enabled: true
  databaseUrl:
    valueFrom:
      secretKeyRef:
        name: pocket-id-db-app
        key: uri
  encryptionKey:
    valueFrom:
      secretKeyRef:
        name: pocket-id-secret
        key: encryption-key
  s3:
    bucket: pocket-id
    region: garage
    endpoint: http://garage.garage-system:3900
    forcePathStyle: true
    accessKeyId:
      valueFrom:
        secretKeyRef:
          name: pocket-id-garage-key
          key: accessKeyID
    secretAccessKey:
      valueFrom:
        secretKeyRef:
          name: pocket-id-garage-key
          key: secretAccessKey
  route:
    enabled: true
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: ListenerSet
        name: external
        namespace: gateway-system
  ui:
    sessionDuration: 1440
  userManagement:
    allowOwnAccountEdit: false
    allowUserSignups: withToken
    emailsVerified: true
