apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/garage-operator/config
  - resources/secret.yaml
patches:
  - path: patches/reference-grant.yaml
  - path: patches/replica.yaml
  - path: patches/web.yaml
  - path: patches/route.yaml
