apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mautrix-bridge
spec:
  values:
    config:
      homeserver:
        domain: uwuity.kind.homelab.test
        address: https://uwuity.kind.homelab.test
      bridge:
        public_address: https://discord.mautrix.kind.homelab.test
        permissions:
          uwuity.kind.homelab.test: user
          "@kasefuchs:uwuity.kind.homelab.test": admin
        direct_media:
          server_name: discord.mautrix.kind.homelab.test
        login_shared_secret_map:
          uwuity.kind.homelab.test: "as_token:$BRIDGE_DOUBLE_PUPPET_AS_TOKEN"
