apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  values:
    nextcloud:
      host: nextcloud.kind.homelab.test
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: ingress.kind.homelab.test
