apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/paperless/app
  - resources/secret.yaml
components:
  - ../../../../components/cnpg/components/backup
patches:
  - path: patches/placement.yaml
