apiVersion: v1
kind: Secret
metadata:
  name: litellm-secret
type: Opaque
stringData:
  LITELLM_SALT_KEY: ENC[AES256_GCM,data:4Y9aF1P0y6D+mZ1hAjvJ++4BedV7t8yp2hBRdlUSY0tqufq/IJr/dkK1uQI=,iv:FpWoS80TZchD6NZYXA3Hxlc/aL9eyJ+McGXr/T4uD7k=,tag:B1u9ov3CJWj+0g4s0bt5Rg==,type:str]
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:S8yO2xSE5tbl9ERxaPdXxrQ2glSMf491YC6NcM3Ea8Sck1MRDXLUi8UybUI=,iv:zwpev3Db0SmuVWqtgA3aSpApaDCIG3AFIPDeg5WKbCc=,tag:fRrdsGm22llBtIHK+DZ1Eg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SVZneU9CbWNSOUc5OFQ4
        UE5vZW5wc2dZSG9EeXJYVnZmbU4wYjVaYlgwCk5SN2VkMTc5ZDJRVkxxNVRnOXBD
        Rko3STF6NWkyVEl3cEZ5TmVqN0F4dnMKLS0tIFFUeVA2cytyNyt0MlRwQU5WL3NQ
        aUkyTlM4YVg1K0VZMzYxRzJoREkzeW8KLzLYda+uyt5i2EECDjIIeKb4EpLEmC8A
        xV+4rd3rkNynRw9FuR38KaWd45LOmx+rFANB+/oWCL+fw4HI7fB0Hg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age194uq3r4zu3kjllp8x947yjk0h0hj33v82qwyged2hczzywrc0spsw9vxer
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-31T18:37:28Z"
  mac: ENC[AES256_GCM,data:WZeqrYZ2VOGiBSvwJmGa506icqJuUIjG8GxFNCzxR/wQ+xGdXzEbQcxQZFdP7p7sNT5Q6BdYTxVeP2avA7mPJqdaCTTCuKu9tmJI6+x8I0oaY2IMJ+OknCBBv6Mr55YfCrYmgg/NoGlu2ywPwUtabAGTVAgqoOCjCjm2qjAtMXk=,iv:ABrU3TatZlR9Rk8cPKR5AwEB82c9GOd9/XeqjM8qPJA=,tag:k9/DkNp8Hrnv2mFs2sQzVg==,type:str]
  version: 3.13.3
