apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wakapi
spec:
  interval: 1h
  releaseName: wakapi
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: wakapi
  values:
    persistence:
      data:
        enabled: false
    route:
      main:
        enabled: true
        hostnames:
          - waka.${CLUSTER_DOMAIN}
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: ListenerSet
            name: external
            namespace: gateway-system
    config:
      server:
        log_format: json
        public_url: https://waka.${CLUSTER_DOMAIN}
      db:
        dialect: postgres
    controllers:
      main:
        containers:
          main:
            env:
              WAKAPI_DB_HOST:
                valueFrom:
                  secretKeyRef:
                    name: wakapi-db-app
                    key: host
              WAKAPI_DB_PORT:
                valueFrom:
                  secretKeyRef:
                    name: wakapi-db-app
                    key: port
              WAKAPI_DB_NAME:
                valueFrom:
                  secretKeyRef:
                    name: wakapi-db-app
                    key: dbname
              WAKAPI_DB_USER:
                valueFrom:
                  secretKeyRef:
                    name: wakapi-db-app
                    key: user
              WAKAPI_DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: wakapi-db-app
                    key: password
