apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
type: Opaque
stringData:
  nextcloud-username: ENC[AES256_GCM,data:o/RBKsZ7V1LZ,iv:uIHmbgxKb1cN18xK+cciQc2h1EXAM88DPCtjDngGu7Y=,tag:cvyI1mZKdFxLo/jB1MrVeQ==,type:str]
  nextcloud-password: ENC[AES256_GCM,data:mOtCsPgTToPT/xajxMOE63px,iv:89SNuirW2QiXJ0DAI27hCEdO5NMIp7v5toojdfSKllI=,tag:7LXhp4p3SKw0sFON0IzVmg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRU1zb29EbzI3alozZ01x
        ZFdCZ2orTWEwL0RhaFpKQjA2Ry9rekVJa0cwCkJyTFYyZ1ppbFQ4bUFQb2N6T2RK
        NGxuZFU0Ty9JaENPV0JScmVkTit6ZUkKLS0tIGJ0TkV0ajlJa0lObjdsNTltOFpy
        R2ZPell2bWMybFpaWlpOc1J5dDdrZU0Kyuj6opiev7Z992Nq2vKuydtaPdPYM6DY
        KlWn8NFXyrDdguc2uzfSVhFdCM1UZwa2OOzG1OYNnEkEKEzm1JuhNg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-03T16:20:54Z"
  mac: ENC[AES256_GCM,data:uX2q/KfrUqOwGjSjcTobTMqvY9yPUBihsDtTSSebXgGNz7ZUiS3IQokPLOralVlEOB/KKwOGCbCNXD39GVseOcU7NdiYcSBqCXYF4scDE0G2fP5WeVfb/aiJywaqUaHIRfU0wQwui1nLHsqPJPpkt7viLHCZ9MbNqu/p/ZkPNNw=,iv:/i8hLq9uGkDIhMIV1AdxInYy05zd7d/Va76vkL+bynQ=,tag:L7Ok+2TYmJpcHBuTPmaFLQ==,type:str]
  version: 3.13.3
