apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
type: Opaque
stringData:
  cloudflare-api-token: ENC[AES256_GCM,data:2nuNa8T1bLLkqY57OskL/kWfeYhxbGYz/I1qlBf3RNW71v7hLYOUu7YwIRE6pKc+Dmnx69Q=,iv:2BXsoJJ7S565eBJWY3roCreympiIwP7Ww+P49OQXtbw=,tag:JCMVib/mnWJuxAxCyUzlYQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWU5FbXV2THZDZEZkYkVm
        Q1ZFWDJWTndGTTF6YXlaZjAxQWQ5QUQ3NFJRCkF1SzFDSC81My9oajR3a2dMU1dM
        WUJsMExOd0Y0NWJIbUtkUkRjbmdGb0kKLS0tIE5jMHl5VGdWZ0lNQ2ZRNHcxaVFy
        RnlWekV1MnRpWHNuTDZmRUlMNWpSMm8KPEjqIHY2LZkJ58GeSa5nUIp26cUP28Yu
        Sbgku5la3MFK3KzcdvuwRjiOyHi6xWrgvtyoBoMlaTSwULwfidHYcQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T10:59:35Z"
  mac: ENC[AES256_GCM,data:qyB0/TL9TE1cu040gMtuAwEeF1bLcNeEakANbQkj/hwFvGP5GTDedOZWv5+Tqu1P/jpffjCDYqjIB3u8TEBRJEPgukkVV2I1jLbVD6OBMSsP0CG43/LL4QflMh8elyIiu4HG/YQxyfV3PMGEmzGxb29AieaG27oWKawab6PRYCM=,iv:FUirbNTndEmpwd66/4T+9o1EnIYjrBp1R2/VOrDgDXs=,tag:4GwzU52Clyyzy++u/+GfMQ==,type:str]
  version: 3.13.3
