apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
type: Opaque
stringData:
  cloudflare-api-key: ENC[AES256_GCM,data:nfnlx9J5r1BJCwnQ445OKjHvI75IUs75qg91RGMzle8/APW3kB9SSYacY2JNTbpOQNYqFhU=,iv:SIJXYzekUEOM9MVte7clCzL+9WheL3fjol13UvkPDBc=,tag:lygkOsPDyyZ4mO2y7eAL5g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWU5FbXV2THZDZEZkYkVm
        Q1ZFWDJWTndGTTF6YXlaZjAxQWQ5QUQ3NFJRCkF1SzFDSC81My9oajR3a2dMU1dM
        WUJsMExOd0Y0NWJIbUtkUkRjbmdGb0kKLS0tIE5jMHl5VGdWZ0lNQ2ZRNHcxaVFy
        RnlWekV1MnRpWHNuTDZmRUlMNWpSMm8KPEjqIHY2LZkJ58GeSa5nUIp26cUP28Yu
        Sbgku5la3MFK3KzcdvuwRjiOyHi6xWrgvtyoBoMlaTSwULwfidHYcQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T21:27:50Z"
  mac: ENC[AES256_GCM,data:WgzGhp20eD6fl5uBVldZ7SccnoLYS3k4rqJfM0VB0qCY0PmktWfvA807UyaKZ2uMu8ESptQNmBDEsFjKwRM7+5PGzDbKMNUAMnFF8OLRRONt1fos3bs5JgTmjh1neEP+UltfT9JdomriZRvFsbpo9VYcYbaXkjLujFWk63aHOKA=,iv:zm+frudtLkr6rZ2ng7DdBX5gnQutDUfULeQ8kPxRF04=,tag:q0fSkWH0ACO5jhBx17y5JA==,type:str]
  version: 3.13.3
