apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: internal
spec:
  blocks:
    - start: 10.45.241.100
      stop: 10.45.241.250
    - start: fd45:45:45:f1::100
      stop: fd45:45:45:f1::250
