apiVersion: v1
kind: Secret
metadata:
  name: codeberg-pac-credentials
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:g4yONhJqwKlphwyxz7u61bn/ldP0IlLBLVGGXU0SFUieaXi1604x1g==,iv:Ko/GWUTf6UwrX+kHVM+pNCJ5BdzKLLXeQ0npHz6r99I=,tag:NFw1kuZFOGaI53Nw38Dx6A==,type:str]
  secret: ENC[AES256_GCM,data:hxDzSpMIHo2gYpkznR7Sl2nnpdTkwi52oDZ6QjIevaX3JoWg0Lcjihb5c28=,iv:Vpn0wf1TBpZPwKnDooO9goNFgk0yxlCPt5GwioF+xFc=,tag:6cJ+5u8OVlbGizf18RU1QQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcXMyVDcyTW0vN1o3MGtr
        MnZUN3luVTl2OW5templa2llMWdWZndvbUE0CnhUekpUQ2hUc2lLQjZXa2E2YUE4
        S0dPc1I2ZE1iL1VYVGpsZThMcHY0UFEKLS0tIFJ0S2dTYjdjY3lKaUlPa0hWdXZ1
        YjFoWkQ4cmtGUnJ5cmU5eGJaQjh4UGcKQHaUeLCIl7XTywkzU8y/JozBT62Uq2CA
        1Eck/DwgZzjpj+2rB7GYn9aVwLsdPFqZ1GTEQ8Yt266KmJZN0lfoDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T09:36:12Z"
  mac: ENC[AES256_GCM,data:0zZ3omyj85Rokm7QAwMmYt/Kyjk3pox8Uc97C5jdIA/rOwqxg7fzctg4m29h18XdYTBKaKr7Dbg3B8iqdlUDwvoYibwv2kg7kbrLTktWQdSXLmd6hYsuhm1hucA/16y4/O/3Y/YDEHlxBjCmKa7Fw4nx4+iNE+SF/+er1ex1AXY=,iv:hk/W2vM8bCt00AQaYcvb/ks4jBDg2caS0dp8/OI3TSc=,tag:2tVx+KLV2yotafJXc9M7SA==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: codeberg-package-credentials
type: Opaque
stringData:
  name: ENC[AES256_GCM,data:EqhnDwzooK9i,iv:fTeDHl13daQ2VlkraCRzRI0nSZZkAd/vXy4osQl9tmY=,tag:oo0jhhWtR/StFjS/9IsKrA==,type:str]
  token: ENC[AES256_GCM,data:H6XYIjLhr6Hv1iMcjP4oTKCwxTdRy5gNQ3BV2QX4J+ze+AdPYNe9og==,iv:IZRylvbtwrlhurXs3NYMDp+5q7DGLUD3ir9GreUQBis=,tag:FUyAzzBdc3TqtmCnQl/B1Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcXMyVDcyTW0vN1o3MGtr
        MnZUN3luVTl2OW5templa2llMWdWZndvbUE0CnhUekpUQ2hUc2lLQjZXa2E2YUE4
        S0dPc1I2ZE1iL1VYVGpsZThMcHY0UFEKLS0tIFJ0S2dTYjdjY3lKaUlPa0hWdXZ1
        YjFoWkQ4cmtGUnJ5cmU5eGJaQjh4UGcKQHaUeLCIl7XTywkzU8y/JozBT62Uq2CA
        1Eck/DwgZzjpj+2rB7GYn9aVwLsdPFqZ1GTEQ8Yt266KmJZN0lfoDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T09:36:12Z"
  mac: ENC[AES256_GCM,data:0zZ3omyj85Rokm7QAwMmYt/Kyjk3pox8Uc97C5jdIA/rOwqxg7fzctg4m29h18XdYTBKaKr7Dbg3B8iqdlUDwvoYibwv2kg7kbrLTktWQdSXLmd6hYsuhm1hucA/16y4/O/3Y/YDEHlxBjCmKa7Fw4nx4+iNE+SF/+er1ex1AXY=,iv:hk/W2vM8bCt00AQaYcvb/ks4jBDg2caS0dp8/OI3TSc=,tag:2tVx+KLV2yotafJXc9M7SA==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: container-registry-credentials
type: Opaque
stringData:
  config.json: ENC[AES256_GCM,data:EjakcPL5irm/0WlHmEHuUnZIh3x1GAGZ+qynfRvFKU+QwfFbhsiIG3/3gZqeJVHpogfyOhj5VrajgIrOKLjbn6Fk3GUO6TrWs1Ct0E6/W9FdROi57QI+fsMfIUFtZncf1t7oOxQxUDhdUXs1gSPDEg/EOToGT0/pBu+lpH1xON1DLjhdGA==,iv:kX+2V+/v58jBvvsf3VfDlxQbRvawvOWUogKLUONseJM=,tag:NUSg4x2snuMOSqNNXsHOBA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcXMyVDcyTW0vN1o3MGtr
        MnZUN3luVTl2OW5templa2llMWdWZndvbUE0CnhUekpUQ2hUc2lLQjZXa2E2YUE4
        S0dPc1I2ZE1iL1VYVGpsZThMcHY0UFEKLS0tIFJ0S2dTYjdjY3lKaUlPa0hWdXZ1
        YjFoWkQ4cmtGUnJ5cmU5eGJaQjh4UGcKQHaUeLCIl7XTywkzU8y/JozBT62Uq2CA
        1Eck/DwgZzjpj+2rB7GYn9aVwLsdPFqZ1GTEQ8Yt266KmJZN0lfoDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T09:36:12Z"
  mac: ENC[AES256_GCM,data:0zZ3omyj85Rokm7QAwMmYt/Kyjk3pox8Uc97C5jdIA/rOwqxg7fzctg4m29h18XdYTBKaKr7Dbg3B8iqdlUDwvoYibwv2kg7kbrLTktWQdSXLmd6hYsuhm1hucA/16y4/O/3Y/YDEHlxBjCmKa7Fw4nx4+iNE+SF/+er1ex1AXY=,iv:hk/W2vM8bCt00AQaYcvb/ks4jBDg2caS0dp8/OI3TSc=,tag:2tVx+KLV2yotafJXc9M7SA==,type:str]
  version: 3.13.3
