apiVersion: v1
kind: Secret
metadata:
  name: codeberg-pac-credentials
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:g4yONhJqwKlphwyxz7u61bn/ldP0IlLBLVGGXU0SFUieaXi1604x1g==,iv:Ko/GWUTf6UwrX+kHVM+pNCJ5BdzKLLXeQ0npHz6r99I=,tag:NFw1kuZFOGaI53Nw38Dx6A==,type:str]
  secret: ENC[AES256_GCM,data:hxDzSpMIHo2gYpkznR7Sl2nnpdTkwi52oDZ6QjIevaX3JoWg0Lcjihb5c28=,iv:Vpn0wf1TBpZPwKnDooO9goNFgk0yxlCPt5GwioF+xFc=,tag:6cJ+5u8OVlbGizf18RU1QQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcXMyVDcyTW0vN1o3MGtr
        MnZUN3luVTl2OW5templa2llMWdWZndvbUE0CnhUekpUQ2hUc2lLQjZXa2E2YUE4
        S0dPc1I2ZE1iL1VYVGpsZThMcHY0UFEKLS0tIFJ0S2dTYjdjY3lKaUlPa0hWdXZ1
        YjFoWkQ4cmtGUnJ5cmU5eGJaQjh4UGcKQHaUeLCIl7XTywkzU8y/JozBT62Uq2CA
        1Eck/DwgZzjpj+2rB7GYn9aVwLsdPFqZ1GTEQ8Yt266KmJZN0lfoDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T16:40:40Z"
  mac: ENC[AES256_GCM,data:4KYrBqSaL+PY5FT3WUyeGgnr1irzO7cSJsAY82YJa1DuaWoaAlD2lU2bjpgqa/HmF47OEFimP1fIMJhQCW00ELwsWcurCYe6f3Nrq/nvZ/xbpNY7paUZng0kHLNSHL3obTdvQN8FJqvnGqPaEUx1auM86CtXsp9d/VzLzHJSAt0=,iv:ES7JkpJ3M9IbMdUkR+IpU+/wjy0uMyFf2w5s4fD3kaA=,tag:Y+WoyVB4ZvYPwFuAgEu+TA==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: codeberg-package-credentials
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:H6XYIjLhr6Hv1iMcjP4oTKCwxTdRy5gNQ3BV2QX4J+ze+AdPYNe9og==,iv:IZRylvbtwrlhurXs3NYMDp+5q7DGLUD3ir9GreUQBis=,tag:FUyAzzBdc3TqtmCnQl/B1Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcXMyVDcyTW0vN1o3MGtr
        MnZUN3luVTl2OW5templa2llMWdWZndvbUE0CnhUekpUQ2hUc2lLQjZXa2E2YUE4
        S0dPc1I2ZE1iL1VYVGpsZThMcHY0UFEKLS0tIFJ0S2dTYjdjY3lKaUlPa0hWdXZ1
        YjFoWkQ4cmtGUnJ5cmU5eGJaQjh4UGcKQHaUeLCIl7XTywkzU8y/JozBT62Uq2CA
        1Eck/DwgZzjpj+2rB7GYn9aVwLsdPFqZ1GTEQ8Yt266KmJZN0lfoDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T16:40:40Z"
  mac: ENC[AES256_GCM,data:4KYrBqSaL+PY5FT3WUyeGgnr1irzO7cSJsAY82YJa1DuaWoaAlD2lU2bjpgqa/HmF47OEFimP1fIMJhQCW00ELwsWcurCYe6f3Nrq/nvZ/xbpNY7paUZng0kHLNSHL3obTdvQN8FJqvnGqPaEUx1auM86CtXsp9d/VzLzHJSAt0=,iv:ES7JkpJ3M9IbMdUkR+IpU+/wjy0uMyFf2w5s4fD3kaA=,tag:Y+WoyVB4ZvYPwFuAgEu+TA==,type:str]
  version: 3.13.3
