apiVersion: v1
kind: Secret
metadata:
  name: codeberg-pac-credentials
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:g4yONhJqwKlphwyxz7u61bn/ldP0IlLBLVGGXU0SFUieaXi1604x1g==,iv:Ko/GWUTf6UwrX+kHVM+pNCJ5BdzKLLXeQ0npHz6r99I=,tag:NFw1kuZFOGaI53Nw38Dx6A==,type:str]
  secret: ENC[AES256_GCM,data:hxDzSpMIHo2gYpkznR7Sl2nnpdTkwi52oDZ6QjIevaX3JoWg0Lcjihb5c28=,iv:Vpn0wf1TBpZPwKnDooO9goNFgk0yxlCPt5GwioF+xFc=,tag:6cJ+5u8OVlbGizf18RU1QQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcXMyVDcyTW0vN1o3MGtr
        MnZUN3luVTl2OW5templa2llMWdWZndvbUE0CnhUekpUQ2hUc2lLQjZXa2E2YUE4
        S0dPc1I2ZE1iL1VYVGpsZThMcHY0UFEKLS0tIFJ0S2dTYjdjY3lKaUlPa0hWdXZ1
        YjFoWkQ4cmtGUnJ5cmU5eGJaQjh4UGcKQHaUeLCIl7XTywkzU8y/JozBT62Uq2CA
        1Eck/DwgZzjpj+2rB7GYn9aVwLsdPFqZ1GTEQ8Yt266KmJZN0lfoDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T18:51:47Z"
  mac: ENC[AES256_GCM,data:THR04LIeR5Ug5rlFZYs/qYMDaJJYGvFCS3eV78/CxIFlGMrGaKey31qXvfU8nY8EdaCCe7eerOo1urU+7rPqE5OtHYMr8XeCQw5waWlzc98JlS7hFlKrCHAZ2JrI3Ipekng/EBalDaRdnDAxXuYznxOFjhaetEhtbxs8WU4SFGI=,iv:e5gtQtIZ9oNXrAbJ7RtmMJ1VZNNoZGHLLhL77PJW6NY=,tag:Nqs0a5CaEwWOHEERkDLx+A==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: codeberg-package-credentials
type: Opaque
stringData:
  name: ENC[AES256_GCM,data:EqhnDwzooK9i,iv:fTeDHl13daQ2VlkraCRzRI0nSZZkAd/vXy4osQl9tmY=,tag:oo0jhhWtR/StFjS/9IsKrA==,type:str]
  token: ENC[AES256_GCM,data:H6XYIjLhr6Hv1iMcjP4oTKCwxTdRy5gNQ3BV2QX4J+ze+AdPYNe9og==,iv:IZRylvbtwrlhurXs3NYMDp+5q7DGLUD3ir9GreUQBis=,tag:FUyAzzBdc3TqtmCnQl/B1Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcXMyVDcyTW0vN1o3MGtr
        MnZUN3luVTl2OW5templa2llMWdWZndvbUE0CnhUekpUQ2hUc2lLQjZXa2E2YUE4
        S0dPc1I2ZE1iL1VYVGpsZThMcHY0UFEKLS0tIFJ0S2dTYjdjY3lKaUlPa0hWdXZ1
        YjFoWkQ4cmtGUnJ5cmU5eGJaQjh4UGcKQHaUeLCIl7XTywkzU8y/JozBT62Uq2CA
        1Eck/DwgZzjpj+2rB7GYn9aVwLsdPFqZ1GTEQ8Yt266KmJZN0lfoDA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T18:51:47Z"
  mac: ENC[AES256_GCM,data:THR04LIeR5Ug5rlFZYs/qYMDaJJYGvFCS3eV78/CxIFlGMrGaKey31qXvfU8nY8EdaCCe7eerOo1urU+7rPqE5OtHYMr8XeCQw5waWlzc98JlS7hFlKrCHAZ2JrI3Ipekng/EBalDaRdnDAxXuYznxOFjhaetEhtbxs8WU4SFGI=,iv:e5gtQtIZ9oNXrAbJ7RtmMJ1VZNNoZGHLLhL77PJW6NY=,tag:Nqs0a5CaEwWOHEERkDLx+A==,type:str]
  version: 3.13.3
