apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: s-ui
spec:
  values:
    ingress:
      main:
        enabled: false
    route:
      main:
        enabled: true
        hostnames:
          - sui.kind.homelab.test
        parentRefs:
          - name: external
            namespace: gateway-system
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
                port: web
          - matches:
              - path:
                  type: PathPrefix
                  value: /sub/
            backendRefs:
              - identifier: main
                port: sub
