apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xray
spec:
  values:
    route:
      vless-xhttp-reality:
        enabled: true
        kind: TLSRoute
        parentRefs:
          - identifier: main
        rules:
          - backendRefs:
              - identifier: vless
                port: xhttp-reality
