apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xray
spec:
  values:
    route:
      vless-xhttp-reality:
        enabled: true
        kind: TLSRoute
        parentRefs:
          - identifier: main
        rules:
          - backendRefs:
              - identifier: vless
                port: xhttp-reality
      vless-grpc:
        enabled: true
        kind: GRPCRoute
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: ListenerSet
            name: external
            namespace: gateway-system
        rules:
          - backendRefs:
              - identifier: vless
                port: grpc
