apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xray
spec:
  values:
    service:
      vless:
        type: ClusterIP
        ports:
          xhttp-reality:
            port: 3000
          reality:
            port: 3004
