---
- op: add
  path: /spec/patches/-
  value:
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: s-ui
    # language="yaml"
    patch: |-
      - op: add
        path: /spec/values/service/inbound
        value:
          enabled: true
          controller: s-ui
          type: NodePort
          ports:
            shadowsocks-udp:
              enabled: true
              protocol: UDP
              port: 8388
