---
- op: add
  path: /spec/patches/-
  value:
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: s-ui
    # language="yaml"
    patch: |-
      - op: add
        path: /spec/values/ingress
        value:
          s-ui:
            enabled: true
            className: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              external-dns.alpha.kubernetes.io/target: silky.kasefuchs.net
            hosts:
              - host: sui.kasefuchs.net
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: s-ui
                      port: panel
                  - path: /sub/
                    pathType: Prefix
                    service:
                      identifier: s-ui
                      port: subscription
            tls:
              - hosts: [sui.kasefuchs.net]
                secretName: s-ui-tls
