---
- op: add
  path: /spec/patches/-
  value:
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: s-ui
    # language="yaml"
    patch: |-
      - op: add
        path: /spec/values/controllers/s-ui/pod
        value:
          nodeSelector:
            net.kasefuchs.homelab/region: cis
            net.kasefuchs.homelab/placement: cloud
