---
- op: add
  path: /spec/patches/-
  value:
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: s-ui
    # language="yaml"
    patch: |-
      - op: add
        path: /spec/values/service/s-ui/ports/reality
        value:
          enabled: true
          port: 2087
      - op: add
        path: /spec/values/rawResources
        value:
          s-ui-reality-route:
            enabled: true
            apiVersion: traefik.io/v1alpha1
            kind: IngressRouteTCP
            spec:
              spec:
                entryPoints: [websecure]
                routes:
                  - services:
                      - name: s-ui
                        port: reality
                tls:
                  passthrough: true
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: Secret
          name: s-ui-secret
          valuesKey: reality_route_match
          targetPath: rawResources.s-ui-reality-route.spec.spec.routes[0].match
