---
- op: add
  path: /spec/patches/-
  value:
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: s-ui
    # language="yaml"
    patch: |-
      - op: add
        path: /spec/values/controllers/usque
        value:
          enabled: true
          type: deployment
          replicas: 1
          pod:
            nodeSelector:
              net.kasefuchs.homelab/region: eu
              net.kasefuchs.homelab/placement: cloud
          containers:
            main:
              image:
                repository: ghcr.io/kasefuchs/containers/usque
                tag: v3.0.0
                pullPolicy: IfNotPresent
              args:
                - -c
                - /etc/usque/config.json
                - socks
                - --always-reconnect
              ports:
                - name: socks
                  protocol: TCP
                  containerPort: 1080
              probes:
                liveness:
                  enabled: true
                  custom: true
                  spec:
                    exec:
                      command:
                        - /bin/sh
                        - -c
                        - "curl -x socks5h://127.0.0.1:1080 -fsS --max-time 5 https://www.google.com/generate_204"
                    initialDelaySeconds: 10
                    periodSeconds: 30
                    timeoutSeconds: 5
                    failureThreshold: 3
      - op: add
        path: /spec/values/service/usque
        value:
          enabled: true
          controller: usque
          type: ClusterIP
          ports:
            socks:
              enabled: true
              port: 1080
      - op: add
        path: /spec/values/persistence/usque-config
        value:
          enabled: true
          type: secret
          name: s-ui-usque-secret
          advancedMounts:
            usque:
              main:
                - path: /etc/usque/
