---
- op: add
  path: /spec/patches/-
  value:
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: s-ui
    # language="yaml"
    patch: |-
      - op: add
        path: /spec/values/controllers/vproxy
        value:
          enabled: true
          type: deployment
          replicas: 1
          pod:
            nodeSelector:
              net.kasefuchs.homelab/region: eu
              net.kasefuchs.homelab/placement: cloud
          containers:
            main:
              image:
                repository: ghcr.io/0x676e67/vproxy
                tag: v2.5.5
                pullPolicy: IfNotPresent
              args:
                - run
                - --bind
                - 0.0.0.0:1080
                - socks5
              ports:
                - name: socks
                  protocol: TCP
                  containerPort: 1080
      - op: add
        path: /spec/values/service/vproxy
        value:
          enabled: true
          controller: vproxy
          type: ClusterIP
          ports:
            socks:
              enabled: true
              port: 1080
