apiVersion: garage.rajsingh.info/v1beta1
kind: GarageReferenceGrant
metadata:
  name: garage
spec:
  from:
    - kind: GarageKey
      namespace: cnpg-system
    - kind: GarageBucket
      namespace: cnpg-system
    - kind: GarageKey
      namespace: pocket-id-system
    - kind: GarageBucket
      namespace: pocket-id-system
    - kind: GarageKey
      namespace: iceshrimp
    - kind: GarageBucket
      namespace: iceshrimp
    - kind: GarageKey
      namespace: matrix-media-repo
    - kind: GarageBucket
      namespace: matrix-media-repo
    - kind: GarageKey
      namespace: vikunja
    - kind: GarageBucket
      namespace: vikunja
    - kind: GarageKey
      namespace: nextcloud
    - kind: GarageBucket
      namespace: nextcloud
