apiVersion: garage.rajsingh.info/v1beta2
kind: GarageCluster
metadata:
  name: garage
spec:
  replication:
    factor: 1
  storage:
    replicas: 0
    nodeLocalPools:
      - name: ssd-250gi
        capacity: 250Gi
        data:
          hostPath: /var/lib/garage/data
          hostPathType: Directory
        metadata:
          hostPath: /var/lib/garage/meta
          hostPathType: Directory
        selector:
          matchLabels:
            garage.rajsingh.info/node-local-pool: ssd-250gi
