apiVersion: v1
kind: Secret
metadata:
  name: sops-age
type: Opaque
stringData:
  kind.agekey: |-
    # created: 2026-07-27T23:53:50+03:00
    # public key: age194uq3r4zu3kjllp8x947yjk0h0hj33v82qwyged2hczzywrc0spsw9vxer
    AGE-SECRET-KEY-10UUDTC5T4UA6K6JKDPPVT6XUDGCCUWJE3E78KHXH6EZ7CFD3P69QLQG8YZ
