apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix-media-repo
spec:
  values:
    config:
      admins:
        - "@kasefuchs:uwuity.floof.fans"
    persistence:
      secrets:
        type: secret
        name: matrix-media-repo-secret
        globalMounts:
          - path: /app/secrets
            readOnly: true
    homeservers:
      uwuity.floof.fans:
        csApi: http://conduwuit-main.conduwuit:6167/
        backoffAt: 10
        adminApiKind: matrix
        signingKeyPath: /app/secrets/uwuity.floof.fans.key
