apiVersion: v1
kind: Secret
metadata:
  name: garage-secret
type: Opaque
stringData:
  admin-token: ENC[AES256_GCM,data:6+TYiI3jFlQVN4ViBj20G2CWk2fs9qBT3KQraw5hR2SxdG6u3xzUkzoh2UCocNB615kuedLdyFHSYLpXxvZPJg==,iv:7Kp1w4k5EhVa6JkRN32GFGuMnsmNWdDMr1obS93grAc=,tag:8Qk8+e4xqxL6LOIMwkejCw==,type:str]
  rpc-secret: ENC[AES256_GCM,data:uHdY4nv6ryA10fB49wg21XTS1KzXHU+GxO8xIkJKzuBYHiqPQcpkpXtU0edspmS3VIV0sfUGzFZmno3CZEfyJA==,iv:ECY1SRu3RdHzJnkE1aYI3IFLq32xL9dhe/fp73u4jgw=,tag:27V0HXBZKOSySTCdRlW2Jw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQM29CTFhRamlDVWJ1UkpF
        bThlUFNxV29GR0NkVGJETk93NDgzRFhBSkhNClRVS1BRdE1aaVI4QisveDJXRU9Z
        NlIvWUJNM3pEejhaakRuMlBCUEk4T1kKLS0tIDFMUlNmVUFzeUV4MmJEMWZ1Nlc2
        azFKN0ZmT0NjUUUycUVUcEQ5VDJaczgK7dx/2/6ExEOLBHHwvn4lfv3tFqMgmVEb
        3qqkcM25nFGHBZ6AYdk7fe5vkfpIyPJ+BDYVjPY6rAguWLj0BabfvQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age194uq3r4zu3kjllp8x947yjk0h0hj33v82qwyged2hczzywrc0spsw9vxer
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-27T22:21:45Z"
  mac: ENC[AES256_GCM,data:WvkTjV2JXJWXcbEEnY5Re5Byj8DQ0B4H0Cda99lg1oRUykamyUu7J3YQQ5C5Dt28JQ5jYF+/lKxonBysT9/PSL8P2ThCqFiQK880ITBT33lwwCZAcysJucz67gWmsrlbrREhNZ6MMy2XHJs3qx33AcObTJGhCsL17dWBAxsp1Og=,iv:vrcpFgprR6hcAIM+OOuRngeqVufAZDeZUfJHuOM0WvE=,tag:5fI73xXMDZ0JjaeRSadVOQ==,type:str]
  version: 3.13.3
