apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-operator
spec:
  interval: 1h
  releaseName: tekton-operator
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: tekton-operator
  values:
    installCRDs: true
    operator:
      autoInstallComponents: false
      defaultTargetNamespace: tekton-system
      additionalEnvs:
        - name: IMAGE_PIPELINES_ARG__SHELL_IMAGE
          value: gcr.io/distroless/base:debug-nonroot@sha256:73532e54641a478ac4a0f8ebbe31e525f2c36af57a2fe10a0a3df69c40c824a6
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault
      runAsNonRoot: true
      runAsUser: 999
      fsGroup: 999
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
