apiVersion: v1
kind: Secret
metadata:
  name: mautrix-bridge-secret
type: Opaque
stringData:
  APPSERVICE_AS_TOKEN: ENC[AES256_GCM,data:VGPqwo6sIyJ7zHIgaowvCEhy8ZeqcrbGWAMX8+v7hSHkUjKvKPxspvKDRDfs0EfMJc7jB/Dx/R7wnDlpJotX1g==,iv:vexbXaBIE46s2YmbsnC2wapt+7Z9F/1SIkrav9YwiCI=,tag:bVwJQW5xAgw5iOkUHw9fQg==,type:str]
  APPSERVICE_HS_TOKEN: ENC[AES256_GCM,data:Tj8sYC+auPnXWuntOlJtOO94RA7JzLyaJK4ORqwvjxHBmZBFSQ70+wOAby50ce+rcISbQmNYqMmTnh3I2cspKw==,iv:4IC3RxRFDpPaH2AFS42vZWI+OWvElMGuF4xhytn2Muc=,tag:Rlql0vV+oMCUj32yhYadFA==,type:str]
  BRIDGE_AVATAR_PROXY_KEY: ENC[AES256_GCM,data:qnP7ui+Nyh23amHFuE95Qlqu1HOKQF/FymWn3/nIN/U=,iv:rl/UdHFwjUfsoPWKFpsmsYtd0WejlzPMwfiIOppytGY=,tag:RKiCw9YNp49xAayh6xP+bw==,type:str]
  BRIDGE_DOUBLE_PUPPET_AS_TOKEN: ENC[AES256_GCM,data:iP12BYCC72F6dzJve7OFyfGjUb0eXt2b9zEE9i0Ud+Ebh4EU/6Jw+Sh/OcA=,iv:0PNVkCi+QbYczn6jf4dJIKJ8a4iNVZXUWglolzvECSw=,tag:TIskhCdH5wtDRXkfh+nxTg==,type:str]
  BRIDGE_DIRECT_MEDIA_SERVER_KEY: ENC[AES256_GCM,data:43zfkPd3z/UHDY6pVkvWwnwsqdmxKN7HFBr5Bd5qumXRC1RPbSkxK1yRIViQK4n6qid4TlsW7Wp7Lw==,iv:CKB3TUuhxT2FlH8q1h9YHJZh/uF1YA+EkMLG6ZlAvm4=,tag:qPk/mUSJC3IbdNv1G9JMag==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OGE4VXRUQlU5OW9KZTd6
        K1NQWXE0SUhjYVp6Y09jZzU0K1ArNUJ3OUFJCnhSQVZHblJzOHVrQzY1Qkk3aVVm
        aG5RT1pMeEFWdXJHWStFQklVUmxtdTgKLS0tIHlibmU0cEsvVHVlZXkzSUVPOTAr
        VUxucjU2YUpFZ2xZK0JnNXoxbEk4UlUKHPV8ty3L43y+dc5VbFfxEUbdLG0JfGWX
        5JZW5G58PWKoW9E7Es0HbCSR+xE4+qk5J6SAP+yBbpIJOqf9ovbUdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-27T18:48:46Z"
  mac: ENC[AES256_GCM,data:1tKHRDfjb9OUNVOdHg7VOsTjnECn0r4QBwe50HnrF6M+cxmQEIr/OJzQH1LuNMGJxrVk/Beea0OgOCE10u6Z7QgAtenVBse3PpWXHxvCUTn2q2OdfyD6NrNMWMrUNQ7ang1fBX9SRzVes8GVSlLin8xN9sMRE7eVuNXcaXbUFG8=,iv:YZGkRsezskUC3KALcDnvzC2gPVq2uePOtW0mWQZNaKA=,tag:kolQE+TvbyeUdb8Hz6Q94w==,type:str]
  version: 3.13.3
