apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/nextcloud/app
  - resources/secret.yaml
patches:
  - path: patches/config.yaml
  - path: patches/storage.yaml
  - path: patches/route.yaml
