apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  values:
    httpRoute:
      enabled: true
      hostnames:
        - podinfo.vagari.homelab.test
      parentRefs:
        - name: external
          namespace: gateway-system
          sectionName: https
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
