apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${NAME}-db
spec:
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: ${NAME}-db
