apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: conduwuit-db-nightly
spec:
  policyRef:
    name: conduwuit-db
  schedule:
    cron: "H 2 * * *"
    jitter: 30m
    runOnCreate: false
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: conduwuit-media-nightly
spec:
  policyRef:
    name: conduwuit-media
  schedule:
    cron: "H 2 * * *"
    jitter: 30m
    runOnCreate: false
