apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: home-assistant-data-nightly
spec:
  policyRef:
    name: home-assistant-data
  schedule:
    cron: "H 2 * * *"
    jitter: 30m
    runOnCreate: false
