apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm-operator
spec:
  interval: 1h
  # temporary use my own fork
  url: oci://ghcr.io/kasefuchs/charts/litellm-operator
  ref:
    tag: "0.0.18"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
