apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/flux-operator
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
    patch: |-
      - op: replace
        path: /spec/path
        value: infrastructure/kind/flux-operator/kustomize
