options {
  directory "/var/cache/bind";
  listen-on port 53 { any; };
  listen-on-v6 port 53 { any; };
  allow-query { any; };
  allow-transfer { any; };
  recursion no;
  dnssec-validation no;
};

key "external-dns" {
  algorithm hmac-sha256;
  secret "96Ah/a2g0/nLeFGK+d/0tzQcccf9hCEIy34PoXX2Qg8=";
};

zone "kind.local." {
  type primary;
  file "/var/lib/bind/db.kind.local";
  allow-update { key external-dns; };
  allow-transfer { key external-dns; };
};
