apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gotosocial-db
spec:
  instances: 1
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      owner: gotosocial
      database: gotosocial
