apiVersion: v1
kind: PersistentVolume
metadata:
  name: gotosocial-garage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: gotosocial-garage
    namespace: gotosocial
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: gotosocial
    volumeAttributes:
      mounter: geesefs
      options: "--no-systemd --memory-limit 500 --dir-mode 0777 --file-mode 0666"
    nodeStageSecretRef:
      name: gotosocial-garage-key
      namespace: gotosocial
    nodePublishSecretRef:
      name: gotosocial-garage-key
      namespace: gotosocial
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotosocial-garage
spec:
  volumeName: gotosocial-garage
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
