apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/xray/app
  - resources/secret.yaml
patches:
  - path: patches/namespace.yaml
  - path: patches/values.yaml
  - path: patches/listener.yaml
  - path: patches/route.yaml
  - path: patches/placement.yaml
  - path: patches/service.yaml
