apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: flux-push-artifact
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-path-change: "[.tekton/flux-push.yaml, flux/***]"
    pipelinesascode.tekton.dev/task: "[git-clone]"
spec:
  params:
    - name: image_name
      value: codeberg.org/kasefuchs/homelab/flux
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: dockerconfig
      secret:
        secretName: container-registry-credentials
  pipelineSpec:
    params:
      - name: image_name
        type: string
    workspaces:
      - name: source
      - name: basic-auth
      - name: dockerconfig
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: url
            value: "{{ repo_url }}"
          - name: revision
            value: "{{ revision }}"
      - name: push-flux-artifact
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source
          - name: dockerconfig
            workspace: dockerconfig
        taskSpec:
          workspaces:
            - name: source
            - name: dockerconfig
          steps:
            - name: flux-push
              image: ghcr.io/fluxcd/flux-cli:v2.9.5
              env:
                - name: DOCKER_CONFIG
                  value: $(workspaces.dockerconfig.path)
              workingDir: $(workspaces.source.path)
              script: |-
                #!/usr/bin/env sh
                set -eu

                flux push artifact "oci://$(params.image_name)" \
                  --path="flux/" \
                  --source="{{ repo_url }}" \
                  --revision="{{ target_branch }}@sha1:{{ revision }}"
