apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cilium/kustomize
  - resources/l2-announcement.yaml
  - resources/ip-pool.yaml
patches:
  - path: patches/kube-proxy.yaml
  - path: patches/hubble.yaml
  - path: patches/l2.yaml
  - path: patches/routing.yaml
