apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: conduwuit
spec:
  values:
    config:
      global:
        new_user_displayname_suffix: "🦊✨"
        server_name: uwuity.vagari.homelab.test
        well_known:
          client: https://uwuity.vagari.homelab.test
          server: uwuity.vagari.homelab.test:443
