apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage-operator
spec:
  interval: 1h
  releaseName: garage-operator
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: garage-operator
  values:
    cosi:
      enabled: true
    webhooks:
      enabled: true
