apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
spec:
  values:
    coder:
      httproute:
        host: coder.kind.homelab.test
        wildcardHost: "*.coder.kind.homelab.test"
