apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-media-repo-db
spec:
  storage:
    size: 1Gi
---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: matrix-media-repo-garage-bucket
spec:
  quotas:
    maxSize: 1Gi
