apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  platforms:
    kubernetes:
      pipelinesAsCode:
        settings:
          tekton-dashboard-url: https://tekton.kind.homelab.test
