apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: iceshrimp-garage-key
spec:
  clusterRef:
    name: garage
    namespace: garage-operator-system
  secretTemplate:
    includeBucketName: true
  bucketPermissions:
    - bucketRef:
        name: iceshrimp-garage-bucket
      read: true
      write: true
