apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iceshrimp
spec:
  interval: 1h
  releaseName: iceshrimp
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: iceshrimp
  values:
    persistence:
      media:
        enabled: false
    config:
      Security:
        Registrations: Invite
      Database:
        Host: "$DB_HOST"
        Port: "$DB_PORT"
        Database: "$DB_NAME"
        Username: "$DB_USER"
        Password: "$DB_PASSWORD"
      Storage:
        Provider: ObjectStorage
        ObjectStorage:
          Endpoint: "$S3_HOST"
          Bucket: "$S3_BUCKET"
          Region: "$S3_REGION"
          KeyId: "$S3_KEY_ID"
          SecretKey: "$S3_SECRET_KEY"
    route:
      main:
        enabled: true
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: ListenerSet
            name: external
            namespace: gateway-system
    controllers:
      main:
        initContainers:
          render-config:
            env:
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-db-app
                    key: host
              - name: DB_PORT
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-db-app
                    key: port
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-db-app
                    key: dbname
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-db-app
                    key: user
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-db-app
                    key: password
              - name: S3_HOST
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-garage-key
                    key: host
              - name: S3_BUCKET
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-garage-key
                    key: bucket
              - name: S3_REGION
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-garage-key
                    key: region
              - name: S3_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-garage-key
                    key: accessKeyID
              - name: S3_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-garage-key
                    key: secretAccessKey
        containers:
          main:
            image:
              repository: ghcr.io/kasefuchs/containers/iceshrimp.net
