apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iceshrimp
spec:
  interval: 1h
  releaseName: iceshrimp
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: iceshrimp
  values:
    config:
      Instance:
        WebDomain: shrimp.${CLUSTER_DOMAIN}
        AccountDomain: shrimp.${CLUSTER_DOMAIN}
      Security:
        Registrations: Invite
        # Allow private Storage::ObjectStorage AccessUrl endpoint
        AllowLocalIPv4: true
        AllowLocalIPv6: true
      Database:
        Host: "$DB_HOST"
        Port: "$DB_PORT"
        Database: "$DB_NAME"
        Username: "$DB_USER"
        Password: "$DB_PASSWORD"
      Storage:
        Provider: ObjectStorage
        ObjectStorage:
          Endpoint: "$S3_HOST"
          Bucket: "$S3_BUCKET"
          Region: "$S3_REGION"
          KeyId: "$S3_ACCESS_KEY_ID"
          SecretKey: "$S3_SECRET_ACCESS_KEY"
          AccessUrl: "$S3_WEBSITE_URL"
          DisableValidation: true
    route:
      main:
        enabled: true
        hostnames:
          - shrimp.${CLUSTER_DOMAIN}
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: ListenerSet
            name: external
            namespace: gateway-system
    persistence:
      data:
        enabled: false
    controllers:
      main:
        initContainers:
          render-config:
            env:
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-db-app
                    key: host
              - name: DB_PORT
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-db-app
                    key: port
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-db-app
                    key: dbname
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-db-app
                    key: user
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: iceshrimp-db-app
                    key: password
            envFrom:
              - secretRef:
                  name: iceshrimp-garage-key
        containers:
          main:
            image:
              repository: ghcr.io/kasefuchs/containers/iceshrimp.net
