apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: iceshrimp
spec:
  interval: 1h
  url: oci://codeberg.org/kasefuchs/helm-charts/iceshrimp
  ref:
    tag: "0.3.1"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
