apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
spec:
  distribution:
    version: 2.x
    registry: ghcr.io/fluxcd
  cluster:
    size: small
    networkPolicy: false
  sync:
    kind: OCIRepository
    ref: latest
    interval: 1h
