apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
spec:
  distribution:
    # renovate: datasource=github-releases depName=fluxcd/flux2
    version: 2.9.5
    registry: ghcr.io/fluxcd
  cluster:
    size: small
    networkPolicy: false
  sync:
    kind: OCIRepository
    ref: latest
    interval: 1h
