---
- op: add
  path: /spec/patches/-
  value:
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: x-ui
    # language="yaml"
    patch: |-
      - op: add
        path: /spec/values/service/main/ports/reality
        value:
          enabled: true
          port: 8443
      - op: add
        path: /spec/values/rawResources
        value:
          reality-route:
            enabled: true
            apiVersion: traefik.io/v1alpha1
            kind: IngressRouteTCP
            spec:
              spec:
                entryPoints:
                  - websecure
                routes:
                  - services:
                      - name: x-ui-main
                        port: reality
                tls:
                  passthrough: true
      - op: add
        path: /spec/valuesFrom/-
        value:
          kind: Secret
          name: x-ui-secret
          valuesKey: reality_route_match
          targetPath: rawResources.reality-route.spec.spec.routes[0].match
