services:
  registry:
    image: registry:2
    restart: unless-stopped
    container_name: homelab-registry
    networks: [kind]
    ports: ["5001:5000"]
  registry-proxy:
    build: {context: "https://github.com/rpardini/docker-registry-proxy.git"}
    restart: unless-stopped
    container_name: homelab-registry-proxy
    networks: [kind]
    volumes:
      - "registry-proxy-cache:/docker_mirror_cache"
      - "registry-proxy-certs:/ca"
    environment:
      ENABLE_MANIFEST_CACHE: true
  dns-init:
    build: {context: dns-init}
    restart: on-failure
    container_name: homelab-dns-init
    network_mode: none
    volumes: ["dns-data:/var/lib/bind"]
  dns:
    build: {context: dns}
    restart: unless-stopped
    depends_on:
      dns-init: {condition: service_completed_successfully}
    container_name: homelab-dns
    networks: [kind]
    ports: ["8053:53/udp", "8053:53/tcp"]
    volumes: ["dns-data:/var/lib/bind"]
    tmpfs: ["/var/cache/bind:mode=777"]
networks:
  kind:
    external: true
volumes:
  dns-data: {}
  registry-proxy-cache: {}
  registry-proxy-certs: {}
