apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  values:
    l2announcements:
      enabled: true
      leaseDuration: 3s
      leaseRenewDeadline: 1s
      leaseRetryPeriod: 500ms
