apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: conduwuit
spec:
  name: Continuwuity
  pkceEnabled: true
  allowedUserGroups:
    - name: conduwuit
  secret:
    name: conduwuit-oidc-credentials
  logo:
    logoUrl: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/continuwuity.svg
