apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 1h
  releaseName: flux-operator
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  chartRef:
    kind: OCIRepository
    name: flux-operator
  values:
    serviceMonitor:
      create: true
    reporting:
      interval: 1m
    web:
      networkPolicy:
        create: false
      config:
        authentication:
          type: Anonymous
          anonymous:
            username: flux
            groups:
              - flux-admin
