---
when:
  - event: push
    branch: main
    path:
      include:
        - .woodpecker/flux-push.yaml
        - flux/**

steps:
  - name: build
    image: ghcr.io/fluxcd/flux-cli:v2.8.3
    environment:
      CODEBERG_API_TOKEN:
        from_secret: CODEBERG_PACKAGE_API_TOKEN
    commands:
      # language="sh"
      - >-
        flux push artifact "oci://codeberg.org/${CI_REPO}/flux"
        --path="flux/"
        --creds="${CI_REPO_OWNER}:$${CODEBERG_API_TOKEN}"
        --source="${CI_REPO_CLONE_URL}"
        --revision="${CI_COMMIT_BRANCH}@sha1:${CI_COMMIT_SHA}"
