apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cosi
  namespace: flux-system
spec:
  path: infrastructure/base/cosi/kustomize
  wait: false
  prune: true
  timeout: 5m
  interval: 1h
  retryInterval: 2m
  targetNamespace: container-object-storage-system
  sourceRef:
    kind: OCIRepository
    name: flux-system
  dependsOn:
    - name: cilium
