apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/conduwuit/app
patches:
  - path: patches/config.yaml
  - path: patches/route.yaml
  - path: patches/media.yaml
  - path: patches/storage.yaml
  - path: patches/placement.yaml
