apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/conduwuit/app
components:
  - ../../../../components/pvc/components/backup
  - ../../../base/conduwuit/app/components/oidc
patches:
  - path: patches/config.yaml
  - path: patches/route.yaml
  - path: patches/oidc.yaml
  - path: patches/placement.yaml
