apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  values:
    hubble:
      ui:
        # not merged yet, but why not?
        # https://github.com/cilium/cilium/pull/46792
        httpRoute:
          enabled: true
          hostnames:
            - hubble.staging.homelab.test
          parentRefs:
            - name: external
              namespace: gateway-system
              sectionName: https
