apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-secret
type: Opaque
stringData:
  encryption-key: ENC[AES256_GCM,data:DJEvx08p6BZNu2DVOMhTk36ox2mI3xH0AKI2HsStFy1HFQ9XKGRRJ2+GhrQ=,iv:aGrK0Qa4DYX/Q3MYcSm64DIfCP45pbRClPwrRvBozGw=,tag:w+vfIVczQDaV5FXX0k+JEg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRlFuYXpaYmNiaUhLKzUy
        RWlHaUl1TmJWby9iNnZwN2hXRysyZXN6bEhjCi8rVVZhMDY0bWJSMVo0MW1DeFJu
        Q3Y4TEtnSU1tU2E0RFlUSURXZDlOK3MKLS0tIGJmcmZzYjdWckZ3MFFlcDhJcUxQ
        aXBxVW5QdWxIcDhieFgxOEpIK3oyVFUKCPim0cVe9+7cVEsul4cyUXjgSqsfEptr
        20qe6wFlZvMdpcr2512nnEYykSWPL2lTkvS99ZYdCN4xl5cxLPBUrQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age194uq3r4zu3kjllp8x947yjk0h0hj33v82qwyged2hczzywrc0spsw9vxer
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-17T21:03:34Z"
  mac: ENC[AES256_GCM,data:gaqqxtS/NZGWIvQhCO/AylAuEFQCtdc16EYoo6KIM/beWdn/EF8OYWpuLIFw9RlWlne1ZywLJcK2b6Z3lJhGpW+JUtU8zT8KxhVGChxZOYrt/R5MlU8PR6NbVq2yqY6m+ODvHQFUjla7r/obgBvT6kEyvvVtKW0oh11bQ5Vjjdw=,iv:QUIYf3tLhoWDG8TrmFYYY0nhWZCJgihBXfb2RxEU9Ks=,tag:CDM4FgDnwJ8gqpKzlV7qQA==,type:str]
  version: 3.13.3
