apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium-internal
spec:
  controllerName: io.cilium/gateway-controller
  parametersRef:
    group: cilium.io
    kind: CiliumGatewayClassConfig
    name: internal
    namespace: gateway-system
---
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: internal
spec:
  service:
    loadBalancerClass: io.cilium/l2-announcer
  telemetry:
    accessLogs:
      - format: JSON
        json:
          gateway: "%CILIUM_GATEWAY_NAMESPACE%/%CILIUM_GATEWAY_NAME%"
          start_time: "%START_TIME%"
          method: "%REQUEST_HEADER(:METHOD)%"
          path: "%REQUEST_HEADER(X-ENVOY-ORIGINAL-PATH?:PATH)%"
          protocol: "%PROTOCOL%"
          response_code: "%RESPONSE_CODE%"
          response_flags: "%RESPONSE_FLAGS%"
          bytes_received: "%BYTES_RECEIVED%"
          bytes_sent: "%BYTES_SENT%"
          duration: "%DURATION%"
          authority: "%REQUEST_HEADER(:AUTHORITY)%"
          upstream_host: "%UPSTREAM_HOST%"
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium-external
spec:
  controllerName: io.cilium/gateway-controller
  parametersRef:
    group: cilium.io
    kind: CiliumGatewayClassConfig
    name: external
    namespace: gateway-system
---
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: external
spec:
  service:
    loadBalancerClass: io.cilium/node
  telemetry:
    accessLogs:
      - format: JSON
        json:
          gateway: "%CILIUM_GATEWAY_NAMESPACE%/%CILIUM_GATEWAY_NAME%"
          start_time: "%START_TIME%"
          method: "%REQUEST_HEADER(:METHOD)%"
          path: "%REQUEST_HEADER(X-ENVOY-ORIGINAL-PATH?:PATH)%"
          protocol: "%PROTOCOL%"
          response_code: "%RESPONSE_CODE%"
          response_flags: "%RESPONSE_FLAGS%"
          bytes_received: "%BYTES_RECEIVED%"
          bytes_sent: "%BYTES_SENT%"
          duration: "%DURATION%"
          authority: "%REQUEST_HEADER(:AUTHORITY)%"
          upstream_host: "%UPSTREAM_HOST%"
