apiVersion: v1
kind: Secret
metadata:
  name: xray-secret
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:K5fHCXcFP5ItXN5kJBdBfCP6XRwVHhOI3TH9lsBB6XueTC2Ete99yhGRUrQXD9p1Cfu3gsDgt/uTO2N8RrfzJSNwhz/yCiCIrLItJuSifynWNwAZmUP/nKjVqK7We8Z1VdVxNkdjI/95YtaP1lkExs3El0nzzmIaSJnpXF2W2kgb1rJR2rvapYJdKTmDNAs4ISXTpIENCYnaWG+222K+C5k1xVyfLsHAiEW+X0waNyB9G6gsEgYtEi6fISk9osARDL53uVsORUrmeIPR7C/uug19Io+H76N0ptuWnbbDqSo7/KcxDQxUw33upw3OIK1rA6l23Gh9PyNuLRJw2qaJMUVpWGWEwQLCnHAJyG9AN6/U9q/IoUPAvvSaBa+xhqGxa1/XLb05rp+HdSGiCbu57qT0k+LmWTnM86pc0ErT8/XD8JxQ2yFOW74T6lEcYiLNBDVkRJuX1DGPEaUtFeyFp1+c+84ORfcAtXmIgX59a11LJVL/6gg9IWU1vIXMbavXnDvOQWGoljnKMUQlQE0NTDy58pIWt80MhhiflpxQnb3XuSvPpONCNBUcfcpsLruuOcPO/ChdgfuwO3049+FGBdz4MDt09//Np0/jdOPzGHM7GU6lIT96gHm8QbVgzRqIgK0uFiXaes1x3suo888Jog/7Y9d1FsFhkFbrg2XNVKGW9SZocq1Y6lLIvWOQ4V4iTNlBFoNL3N6I+Tvv6OA5UPRVJWHigwMEBBrmynGaMaCmOFbHORCY0bEMct9dJ2CMh4cBdgVZFiycZmpzQD+Xd7pyERZ8HoFHeWNyFm1b3fDDh7LjdROpgCWGieybpbT8bLO13VPi8KlOdeP/nKnmQPsvARAk6LRDWJM2Jg4ORUEEo3Ip1nc4il7lZSniW9MRCAVk/dMRtonLJNmaSy/Ll5eFxLC1arh70gdmYYbhDpFrhETma1E2byFCDRF+MZcjR6juQt/mx2HwEBdaQaI7J/Cm8Qwm2fzn5URp/kXHK9gDpZj8POBi8n9eGPnbIpQ+WX1k0f1diFPGfkZNASyHxVCDUdwsMAvV5JbhkIQ5VFr8jEip3HsAvmvdandfxWi90L3CVXTRNYP5gmpm+bDPFDhblJvjcKydP6NjQ0q3LkQe6hIkm+0vVYUMcfZ8lC7dQ9JUPJFRRWCNNN9ZNcG9bvqX9xjD0Ar4HRB3p45wyHg8R7cB1xtT4gmFZ6RSkriX8VUy9MZU+EyC0IyAcBKww01w1/fiEZ5Vow/fs36HWJiW0aMSthrNGnIrdr9RFlapwxEE0JIpxJq2xDJf/92bXqfhryMeEvioi8Ueb4/3xQxjEckhtiJ11qRc6AEXrZboIAR+bDAecDfDVoSM8sVk/6vfdZbokPatg6WODc5vcewpGEMWCXEaEos2F9ffrvIGdyRqZpUyO8BDee4NG3gj0DDEFxBwynz0wgTJNZPWGoxarqxAQlnI6oh38gUZs1vbXIEGv3z5cgslgYYAioJK9qTojXAbHeZ0Vtc28hpNNX/Ivq2GK1pP41PJqwq4,iv:Q1t0ZcmnuuaSCbU3qmJxhHRlmD6ClsUKPE7DoIsodaw=,tag:A21Xfv9Fh0JoPVPGYGfPJg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RWh2TDZMUnh4YWNqZHAv
        Ny9vdHVkK0RwZUt1ME4vZkF1UEkrK3I1V0hZCjJERXRyVDZETkN4aDBuMm1kYkhI
        SkFKdmhNZHpUWldIWGRibFF5Nk5oRnMKLS0tIDRMQ1FpcU1BU3o3c29QN0tGSkNj
        TEFjSVN1YTZZUStJZ3hST1pIZ0JXTXMKDqxFS3pxXMypmS9ErpsstT5oWxRzd8NU
        DYn6F0UJhFmd0fJjtRRY1EmpEw7+YNYIoqUmrTR4C8izqVTfPI1gZw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T21:09:20Z"
  mac: ENC[AES256_GCM,data:9KxkEnX1lLVQedaigTOC5nlNJkZdC1f5/qNP84PCw8QixOTXwk9bIECQnpAIvrgMGDKFCfmHiEZjvJRkapg7ze1lDeDE3cB6pG/ggYDCfjzgWucK0XzPqWdiFZiI4CdIdbrz2N8Ft102OURcQMiRTMYJodvf03zXkRISgDK8G88=,iv:Dew8TzYt6k+LQHbmv3auiEafFM8ejcOxsEomjFNtpZo=,tag:RRD05S75sedu/4TrEdHHrA==,type:str]
  version: 3.13.3
