---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/secret.yaml
  - resources/usque-secret.yaml
  - ../../../../base/s-ui
patches:
  - path: patches/ingress.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
  - path: patches/placement.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
  - path: patches/usque.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
  - path: patches/reality.yaml
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
