apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/opencloud/app
components:
  - ../../../base/opencloud/app/components/oidc
patches:
  - path: patches/trust.yaml
