---
k3s_agent_config:
  node-ip: 10.45.0.34
  node-external-ip: 85.208.85.159

  server: https://10.45.0.33:6443
  token: "{{ k3s_agent_config_token }}"

  node-label:
    - net.kasefuchs.homelab/region=cis
    - net.kasefuchs.homelab/placement=cloud

  flannel-iface: awg0
