apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/victoria-metrics
patches:
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: victoria-metrics-controller
        namespace: flux-system
      spec:
        path: infrastructure/kind/victoria-metrics/controller
