apiVersion: garage.rajsingh.info/v1beta1
kind: GarageBucket
metadata:
  name: vikunja-garage-bucket
spec:
  globalAlias: vikunja
  clusterRef:
    name: garage
    namespace: garage-operator-system
  quotas:
    maxSize: 20Gi
