apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: vikunja-garage-key
spec:
  clusterRef:
    name: garage
    namespace: garage-operator-system
  secretTemplate:
    includeBucketName: true
    accessKeyIdKey: accessKeyID
    secretAccessKeyKey: secretAccessKey
  bucketPermissions:
    - bucketRef:
        name: vikunja-garage-bucket
      read: true
      write: true
