apiVersion: v1
kind: Namespace
metadata:
  name: vikunja
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    gateway.networking.k8s.io/route-access-external: "true"
    kopiur.home-operations.com/repository-access-external: "true"
