apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vikunja
spec:
  interval: 1h
  url: oci://codeberg.org/kasefuchs/helm-charts/vikunja
  ref:
    tag: "0.1.0"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
