apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage-s3
spec:
  hostnames:
    - s3.garage.vagari.homelab.test
    - "*.s3.garage.vagari.homelab.test"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage-web
spec:
  hostnames:
    - "*.web.garage.vagari.homelab.test"
