# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopiur-controller
spec:
  path: infrastructure/base/kopiur/controller
  wait: true
  prune: true
  timeout: 10m
  interval: 1h
  retryInterval: 2m
  targetNamespace: kopiur-system
  sourceRef:
    kind: OCIRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      NAME: kopiur
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopiur-config
spec:
  path: infrastructure/base/kopiur/config
  wait: true
  prune: true
  timeout: 10m
  interval: 1h
  retryInterval: 2m
  targetNamespace: kopiur-system
  sourceRef:
    kind: OCIRepository
    name: flux-system
  dependsOn:
    - name: kopiur-controller
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      NAME: kopiur
