apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/tekton-operator
patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      name: tekton-operator-config
    patch: |-
      - op: replace
        path: /spec/path
        value: infrastructure/kind/tekton-operator/config
