apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: kopiur
spec:
  encryption:
    passwordSecretRef:
      namespace: kopiur-system
      name: kopiur-secret
      key: KOPIA_PASSWORD
  allowedNamespaces:
    selector:
      matchLabels:
        kopiur.home-operations.com/repository-access: "true"
  credentialProjection:
    allowed: true
  maintenance:
    namespace: kopiur-system
