apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: external
spec:
  encryption:
    passwordSecretRef:
      namespace: kopiur-system
      name: kopiur-secret
      key: KOPIA_PASSWORD
  allowedNamespaces:
    selector:
      matchLabels:
        kopiur.home-operations.com/repository-access-external: "true"
  credentialProjection:
    allowed: true
  server:
    namespace: kopiur-system
  maintenance:
    namespace: kopiur-system
