apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/namespace.yaml
  - resources/flux-kustomization.yaml
  - resources/git-repository.yaml
  - resources/gateway.yaml
