---
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: enabled
    fluxcd.controlplane.io/reconcileEvery: 1h
    fluxcd.controlplane.io/reconcileTimeout: 5m
spec:
  distribution:
    version: 2.7.x
    registry: ghcr.io/fluxcd
    artifact: oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
  cluster:
    type: kubernetes
    size: small
    domain: cluster.local
    multitenant: false
    networkPolicy: true
  sync:
    kind: OCIRepository
    url: oci://codeberg.org/kasefuchs/homelab/flux
    ref: latest
    path: clusters/production/flux-system
    interval: 1h
